# Generated by Django 6.0.5 on 2026-06-10 15:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_historique", "0002_colleguelogentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetaction",
            name="deactivation_reason",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="projetaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("status_change", "Changement de statut"),
                    ("doc_generated", "Génération de document"),
                    ("doc_modified", "Modification de document"),
                    ("doc_deleted", "Suppression de document généré"),
                    ("doc_uploaded", "Import de document"),
                    ("doc_upload_deleted", "Suppression de document importé"),
                    ("notified", "Notification"),
                    ("assiette_modified", "Modification de l'assiette"),
                    ("dotation_added", "Ajout de dotation"),
                    ("dotation_removed", "Suppression de dotation"),
                    ("montant_modified", "Modification du montant"),
                    ("boolean_modified", "Modification de booléen"),
                    ("depot_dossier", "Dépôt du dossier"),
                    ("passage_en_instruction", "Passage en instruction"),
                    ("retour_en_construction", "Retour en construction"),
                    ("deactivation", "Désactivation du dossier"),
                    ("reactivation", "Réactivation du dossier"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="projetaction",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
