# Generated by Django 6.0.7 on 2026-08-31 13:55

import gsl.historique.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_historique", "0004_backfill_depot_and_instruction_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetaction",
            name="notification_document",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=gsl.historique.models.projet_action_document_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="projetaction",
            name="notification_motivation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
