# Generated by Django 6.0.7 on 2026-09-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_historique", "0006_delete_spurious_retour_en_construction_actions"),
    ]

    operations = [
        migrations.AddField(
            model_name="projetaction",
            name="source_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Identifiant de l'événement source (ex : id du Traitement DN), pour éviter les doublons lors d'une resynchronisation.",
                max_length=64,
                verbose_name="Identifiant externe",
            ),
        ),
    ]
