# Generated by Django 6.0.7 on 2026-09-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_historique", "0006_delete_spurious_retour_en_construction_actions"),
        ("gsl_projet", "0041_enveloppe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projetaction",
            name="enveloppe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_projet.enveloppe",
            ),
        ),
    ]
