# Generated by Django 6.0.7 on 2026-09-17 18:08

from django.db import migrations

REMOVED_ACTION_TYPES = [
    "retour_en_construction",
    "passage_en_instruction",
    "retour_en_instruction",
    "depot_dossier",
]


def remove_some_traitements_projet_actions(apps, schema_editor):
    """
    Ces types de ProjetAction sont désormais reconstruits de façon fiable à
    partir de l'historique complet des traitements DN du dossier
    (ProjetActionManager.create_from_dossier_traitements, rejoué à chaque
    resynchronisation) : on supprime les entrées issues de l'ancien
    mécanisme (heuristique de comparaison de dates), pour qu'elles soient
    recréées proprement au prochain sync de chaque dossier.
    """
    ProjetAction = apps.get_model("gsl_historique", "ProjetAction")
    ProjetAction.objects.filter(action_type__in=REMOVED_ACTION_TYPES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_historique", "0008_alter_projetaction_action_type"),
    ]

    operations = [
        migrations.RunPython(
            remove_some_traitements_projet_actions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
