# Generated by Django 6.0.8 on 2026-10-09 08:51

from django.db import migrations

TYPE_DEACTIVATION = "deactivation"
TYPE_REACTIVATION = "reactivation"
RAISON_ARCHIVE = "archive"


def delete_archive_projet_actions(apps, schema_editor):
    """
    L'archivage sur DN n'est plus suivi dans Turgot : on supprime les
    désactivations pour cause d'archivage, ainsi que les réactivations qui
    les suivent (une réactivation n'a pas de details, on se fie donc à la
    dernière désactivation du projet qui la précède).
    """
    ProjetAction = apps.get_model("gsl_historique", "ProjetAction")
    actions = ProjetAction.objects.filter(
        action_type__in=(TYPE_DEACTIVATION, TYPE_REACTIVATION)
    ).order_by("projet_id", "created_at", "id")

    to_delete = []
    previous_projet_id = None
    last_deactivation_details = None
    for action in actions.iterator():
        if action.projet_id != previous_projet_id:
            previous_projet_id = action.projet_id
            last_deactivation_details = None

        if action.action_type == TYPE_DEACTIVATION:
            last_deactivation_details = action.details
            if action.details == RAISON_ARCHIVE:
                to_delete.append(action.id)
        elif last_deactivation_details == RAISON_ARCHIVE:
            to_delete.append(action.id)
            last_deactivation_details = None

    ProjetAction.objects.filter(id__in=to_delete).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_historique", "0009_remove_some_traitements_projet_actions"),
    ]

    operations = [
        migrations.RunPython(
            delete_archive_projet_actions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
