# Generated by Django 6.0.5 on 2026-06-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0016_alter_departement_active"),
        ("gsl_suivi_financier", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubventionFondsVert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dossier_number",
                    models.IntegerField(
                        unique=True, verbose_name="Numéro de dossier DS"
                    ),
                ),
                (
                    "annee_millesime",
                    models.PositiveSmallIntegerField(verbose_name="Millésime"),
                ),
                (
                    "demarche_number",
                    models.IntegerField(verbose_name="Numéro de démarche DS"),
                ),
                (
                    "demarche_title",
                    models.CharField(max_length=200, verbose_name="Démarche"),
                ),
                ("nom_du_projet", models.TextField(verbose_name="Intitulé du projet")),
                ("statut", models.CharField(max_length=30, verbose_name="Statut")),
                (
                    "montant_aide_demandee",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant demandé"
                    ),
                ),
                (
                    "montant_subvention_attribuee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant attribué",
                    ),
                ),
                (
                    "total_des_depenses",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Coût total"
                    ),
                ),
                (
                    "date_depot",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de dépôt"
                    ),
                ),
                (
                    "date_notification",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de notification"
                    ),
                ),
                (
                    "beneficiaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_suivi_financier.beneficiaire",
                        verbose_name="Bénéficiaire",
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.commune",
                        verbose_name="Commune",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subvention Fonds Vert",
                "verbose_name_plural": "Subventions Fonds Vert",
                "ordering": ["-annee_millesime"],
            },
        ),
    ]
