from django.urls import path

from gsl_notification.views.decorators import (
    document_visible_by_user,
)
from gsl_notification.views.generate_document_for_multiple_projets_views import (
    choose_type_for_multiple_document_generation,
    download_documents,
    save_documents,
    select_modele_multiple,
)
from gsl_notification.views.modele_views import (
    ChooseModeleDocumentType,
    CreateModelDocumentWizard,
    DuplicateModele,
    ModeleListView,
    UpdateModele,
    delete_modele_view,
    get_generic_modele,
)
from gsl_notification.views.uploaded_document_views import (
    choose_type_for_document_upload,
    create_uploaded_document_view,
    delete_uploaded_document_view,
    download_uploaded_document,
    view_uploaded_document,
)
from gsl_notification.views.views import (
    DownloadDocumentView,
    PrintDocumentView,
    change_document_view,
    choose_type_for_document_generation,
    delete_document_view,
    documents_view,
    select_modele,
)

urlpatterns = [
    path(
        "<int:programmation_projet_id>/documents/",
        documents_view,
        name="documents",
    ),
    # Generated files
    path(
        "<int:programmation_projet_id>/choix-du-type/",
        choose_type_for_document_generation,
        name="choose-generated-document-type",
    ),
    path(
        "<int:programmation_projet_id>/selection-d-un-modele/<str:document_type>",
        select_modele,
        name="select-modele",
    ),
    path(
        "<int:programmation_projet_id>/modifier-document/<str:document_type>",
        change_document_view,
        name="modifier-document",
    ),
    path(
        "document/<str:document_type>/<int:document_id>/download/",
        document_visible_by_user(DownloadDocumentView.as_view()),
        name="document-download",
    ),
    path(
        "document/<str:document_type>/<int:document_id>/view/",
        document_visible_by_user(PrintDocumentView.as_view()),
        name="document-view",
    ),
    path(
        "document/<str:document_type>/<int:document_id>/delete/",
        delete_document_view,
        name="delete-document",
    ),
    # Generated files for multiple projets
    path(
        "<str:dotation>/choix-du-type/",
        choose_type_for_multiple_document_generation,
        name="choose-generated-document-type-multiple",
    ),
    path(
        "<str:dotation>/selection-d-un-modele/<str:document_type>",
        select_modele_multiple,
        name="select-modele-multiple",
    ),
    path(
        "<str:dotation>/sauvegarde/<str:document_type>/<int:modele_id>",
        save_documents,
        name="save-documents",
    ),
    path(
        "<str:dotation>/telechargement/<str:document_type>",
        download_documents,
        name="download-documents",
    ),
    # Uploaded files
    path(
        "<int:programmation_projet_id>/televersement/choix-du-type/",
        choose_type_for_document_upload,
        name="choose-uploaded-document-type",
    ),
    path(
        "<int:programmation_projet_id>/televersement/<str:document_type>/creer/",
        create_uploaded_document_view,
        name="upload-a-document",
    ),
    path(
        "document-televerse/<str:document_type>/<int:document_id>/download/",
        download_uploaded_document,
        name="uploaded-document-download",
    ),
    path(
        "document-televerse/<str:document_type>/<int:document_id>/view/",
        view_uploaded_document,
        name="uploaded-document-view",
    ),
    path(
        "document-televerse/<str:document_type>/<int:document_id>/delete/",
        delete_uploaded_document_view,
        name="delete-uploaded-document",
    ),
    # Modèles d'arrêtés
    path(
        "modeles/liste/<str:dotation>/",
        ModeleListView.as_view(),
        name="modele-liste",
    ),
    path(
        "modeles/nouveau/<str:dotation>/",
        ChooseModeleDocumentType.as_view(),
        name="modele-creer-choix-du-type",
    ),
    path(
        "modeles/nouveau/<str:modele_type>/<str:dotation>/",
        CreateModelDocumentWizard.as_view(),
        name="modele-creer",
    ),
    path(
        "modeles/modifier/<str:modele_type>/<str:modele_id>/",
        UpdateModele.as_view(),
        name="modele-modifier",
    ),
    path(
        "modeles/dupliquer/<str:modele_type>/<str:modele_id>/",
        DuplicateModele.as_view(),
        name="modele-dupliquer",
    ),
    path(
        "modeles/generique/<str:dotation>/",
        get_generic_modele,
        name="get-generic-modele-template",
    ),
    path(
        "modeles/<str:modele_type>/<str:modele_id>/",
        delete_modele_view,
        name="delete-modele",
    ),
]
