from django.urls import path

from gsl_notification.views.decorators import (
    document_visible_by_user,
)
from gsl_notification.views.modele_views import (
    ChooseModeleDocumentType,
    CreateModelDocumentWizard,
    DuplicateModele,
    ModeleListView,
    UpdateModele,
    delete_modele_view,
    get_generic_modele,
)
from gsl_notification.views.upload_document_views import (
    create_arrete_signe_view,
    delete_arrete_signe_view,
    download_arrete_signe,
    view_arrete_signe,
)
from gsl_notification.views.views import (
    DownloadArreteView,
    PrintDocumentView,
    change_document_view,
    choose_type_for_document_generation,
    delete_document_view,
    documents_view,
    select_modele,
)

urlpatterns = [
    path(
        "<int:programmation_projet_id>/documents/",
        documents_view,
        name="documents",
    ),
    # Arretes
    path(
        "<int:programmation_projet_id>/choix-du-type/",
        choose_type_for_document_generation,
        name="choose-generated-document-type",
    ),
    path(
        "<int:programmation_projet_id>/selection-d-un-modele/<str:document_type>",
        select_modele,
        name="select-modele",
    ),
    path(
        "<int:programmation_projet_id>/modifier-document/<str:document_type>",
        change_document_view,
        name="modifier-document",
    ),
    path(
        "document/<str:document_type>/<int:document_id>/download/",
        document_visible_by_user(DownloadArreteView.as_view()),
        name="document-download",
    ),
    path(
        "document/<str:document_type>/<int:document_id>/view/",
        document_visible_by_user(PrintDocumentView.as_view()),
        name="document-view",
    ),
    path(
        "document/<str:document_type>/<int:document_id>/delete/",
        delete_document_view,
        name="delete-document",
    ),
    # Arretes signés
    path(
        "<int:programmation_projet_id>/creer-arrete-signe/",
        create_arrete_signe_view,
        name="create-arrete-signe",
    ),
    path(
        "arrete-signe/<int:arrete_signe_id>/download/",
        download_arrete_signe,
        name="arrete-signe-download",
    ),
    path(
        "arrete-signe/<int:arrete_signe_id>/view/",
        view_arrete_signe,
        name="arrete-signe-view",
    ),
    path(
        "arrete-signe/<int:arrete_signe_id>/delete/",
        delete_arrete_signe_view,
        name="delete-arrete-signe",
    ),
    # Modèles d'arrêtés
    path(
        "modeles/liste/<str:dotation>/",
        ModeleListView.as_view(),
        name="modele-liste",
    ),
    path(
        "modeles/nouveau/<str:dotation>/",
        ChooseModeleDocumentType.as_view(),
        name="modele-creer-choix-du-type",
    ),
    path(
        "modeles/nouveau/<str:modele_type>/<str:dotation>/",
        CreateModelDocumentWizard.as_view(),
        name="modele-creer",
    ),
    path(
        "modeles/modifier/<str:modele_type>/<str:modele_id>/",
        UpdateModele.as_view(),
        name="modele-modifier",
    ),
    path(
        "modeles/dupliquer/<str:modele_type>/<str:modele_id>/",
        DuplicateModele.as_view(),
        name="modele-dupliquer",
    ),
    path(
        "modeles/<str:modele_type>/<str:modele_id>/",
        delete_modele_view,
        name="delete-modele",
    ),
    path(
        "modeles/generique/<str:dotation>/",
        get_generic_modele,
        name="get-generic-modele-template",
    ),
]
