# Generated by Django 5.1.1 on 2024-11-08 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0004_alter_adresse_commune_alter_adresse_postal_code_and_more"),
        ("gsl_demarches_simplifiees", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="projet_adresse",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.adresse",
            ),
        ),
    ]
