# Generated by Django 5.1.1 on 2024-11-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0004_alter_adresse_commune_alter_adresse_postal_code_and_more"),
        (
            "gsl_demarches_simplifiees",
            "0004_formejuridique_naf_personnemorale_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profil DS", "verbose_name_plural": "Profils DS"},
        ),
        migrations.AlterField(
            model_name="dossier",
            name="projet_adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.adresse",
            ),
        ),
        migrations.AlterField(
            model_name="personnemorale",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.adresse",
                verbose_name="Adresse",
            ),
        ),
    ]
