# Generated by Django 5.1.4 on 2024-12-20 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0006_commune_arrondissement"),
        (
            "gsl_demarches_simplifiees",
            "0005_alter_profile_options_alter_dossier_projet_adresse_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arrondissement",
            options={
                "verbose_name": "Arrondissement DS",
                "verbose_name_plural": "Arrondissements DS",
            },
        ),
        migrations.AddField(
            model_name="arrondissement",
            name="core_arrondissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ds_arrondissements",
                to="gsl_core.arrondissement",
                verbose_name="Arrondissement INSEE",
            ),
        ),
    ]
