# Generated by Django 5.1.4 on 2025-01-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0006_alter_arrondissement_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="ds_date_traitement",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de passage à l’état « Accepté », « Refusé » ou « Classé sans suite », le cas échéant.",
                null=True,
                verbose_name="Date de traitement",
            ),
        ),
    ]
