# Generated by Django 5.1.4 on 2025-01-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0007_dossier_ds_date_traitement"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="annotations_assiette",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant des dépenses éligibles retenues (€)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_champ_libre",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_contact",
            field=models.CharField(
                blank=True,
                verbose_name="Contact de l'agent instructeur à indiquer au demandeur",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_dotation",
            field=models.CharField(
                blank=True,
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                verbose_name="Imputation budgétaire - Choix de la dotation",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_budget_vert",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet concourant à la transition écologique au sens budget vert",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_crte",
            field=models.BooleanField(
                null=True, verbose_name="Projet rattaché à un CRTE"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_qpv",
            field=models.BooleanField(null=True, verbose_name="Projet situé en QPV"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_montant_accorde",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant définitif de la subvention (€)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_taux",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Taux de subvention (%)",
            ),
        ),
    ]
