# Generated by Django 5.1.4 on 2025-01-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0008_dossier_annotations_assiette_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demarche",
            name="raw_ds_data",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Données DS brutes"
            ),
        ),
    ]
