# Generated by Django 5.1.4 on 2025-01-31 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_demarches_simplifiees", "0009_demarche_raw_ds_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="projet_adresse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.adresse",
                verbose_name="Adresse principale du projet",
            ),
        ),
    ]
