# Generated by Django 5.1.4 on 2025-02-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0011_alter_dossier_annotations_assiette_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="annotations_dotation",
            field=models.CharField(
                blank=True, verbose_name="Imputation budgétaire - Choix de la dotation"
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_dispositif_sollicite",
            field=models.CharField(
                blank=True, verbose_name="Dispositif de financement sollicité"
            ),
        ),
    ]
