# Generated by Django 5.1.7 on 2025-03-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0012_alter_dossier_annotations_dotation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="natureporteurprojet",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("epci", "EPCI"),
                    ("communes", "Communes"),
                    ("autre", "Autre"),
                ],
                max_length=8,
            ),
        ),
    ]
