# Generated by Django 5.1.7 on 2025-03-19 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0013_natureporteurprojet_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="natureporteurprojet",
            options={
                "verbose_name": "Nature du porteur de projet",
                "verbose_name_plural": "Natures de porteur de projet",
            },
        ),
    ]
