# Generated by Django 5.1.7 on 2025-03-25 15:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0014_alter_natureporteurprojet_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="critereeligibilitedetr",
            options={
                "verbose_name": "Catégorie DETR",
                "verbose_name_plural": "Catégories DETR",
            },
        ),
        migrations.AlterModelOptions(
            name="critereeligibilitedsil",
            options={
                "verbose_name": "Catégorie DSIL",
                "verbose_name_plural": "Catégories DSIL",
            },
        ),
    ]
