# Generated by Django 5.2.1 on 2025-05-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0015_alter_critereeligibilitedetr_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="critereeligibilitedetr",
            name="demarche",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.demarche",
                verbose_name="Démarche",
            ),
        ),
        migrations.AddField(
            model_name="critereeligibilitedetr",
            name="demarche_revision",
            field=models.CharField(blank=True, default="", verbose_name="Révision"),
        ),
    ]
