# Generated by Django 5.1.7 on 2025-04-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0016_critereeligibilitedetr_demarche_and_more"),
        ("gsl_projet", "0019_alter_dotationprojet_options_categoriedetr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="critereeligibilitedetr",
            name="detr_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_projet.categoriedetr",
                verbose_name="Catégorie d’opération DETR",
            ),
        ),
    ]
