# Generated by Django 5.2.1 on 2025-05-26 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_demarches_simplifiees", "0016_critereeligibilitedetr_demarche_and_more"),
        ("gsl_projet", "0022_alter_dotationprojet_options_categoriedetr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="critereeligibilitedetr",
            name="detr_category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_projet.categoriedetr",
                verbose_name="Catégorie d’opération DETR",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="active_revision_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de publication de la révision active",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="active_revision_id",
            field=models.CharField(
                blank=True,
                default="",
                verbose_name="Identifiant de la révision DS active",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="perimetre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.perimetre",
                verbose_name="Périmètre",
            ),
        ),
        migrations.AlterField(
            model_name="critereeligibilitedetr",
            name="label",
            field=models.CharField(verbose_name="Libellé"),
        ),
        migrations.AddConstraint(
            model_name="critereeligibilitedetr",
            constraint=models.UniqueConstraint(
                fields=("label", "demarche", "demarche_revision"),
                name="unique_critereeligibilitedetr_label_per_demarche_revision",
                nulls_distinct=False,
            ),
        ),
    ]
