# Generated by Django 5.1.7 on 2025-05-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0017_critereeligibilitedetr_detr_category"),
        ("gsl_projet", "0022_merge_20250512_1040"),
    ]

    operations = [
        migrations.AddField(
            model_name="critereeligibilitedetr",
            name="tri",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Numéro d’ordre"
            ),
        ),
        migrations.AlterField(
            model_name="critereeligibilitedetr",
            name="label",
            field=models.CharField(verbose_name="Libellé"),
        ),
        migrations.AddConstraint(
            model_name="critereeligibilitedetr",
            constraint=models.UniqueConstraint(
                fields=("label", "demarche", "demarche_revision"),
                name="unique_critereeligibilitedetr_label_per_demarche_revision",
                nulls_distinct=False,
            ),
        ),
    ]
