# Generated by Django 5.2.7 on 2025-10-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0017_critereeligibilitedetr_detr_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="ds_email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
    ]
