# Generated by Django 5.2.6 on 2025-10-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0017_critereeligibilitedetr_detr_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="ds_instructeurs",
            field=models.ManyToManyField(to="gsl_demarches_simplifiees.profile"),
        ),
    ]
