# Generated by Django 5.2.1 on 2025-05-26 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_demarches_simplifiees", "0018_critereeligibilitedetr_tri_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demarche",
            name="active_revision_date",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de publication de la révision active",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="active_revision_id",
            field=models.CharField(
                blank=True,
                default="",
                verbose_name="Identifiant de la révision DS active",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="perimetre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.perimetre",
                verbose_name="Périmètre",
            ),
        ),
    ]
