# Generated by Django 5.2.7 on 2025-10-23 14:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0018_alter_profile_ds_email"),
        ("gsl_demarches_simplifiees", "0018_dossier_ds_instructeurs"),
    ]

    operations = []
