# Generated by Django 5.2.7 on 2025-11-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0019_merge_20251023_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="demarche",
            name="updated_since",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Date de dernière mise à jour des dossiers",
            ),
        ),
    ]
