# Generated by Django 5.2.7 on 2025-11-06 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0011_alter_collegue_email"),
        ("gsl_demarches_simplifiees", "0019_merge_20251023_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="demandeur_arrondissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_core.arrondissement",
                verbose_name="Arrondissement du demandeur",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="demandeur_departement_or_collectivite",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_core.departement",
                verbose_name="Département ou collectivité du demandeur",
            ),
        ),
    ]
