# Generated by Django 5.2.7 on 2025-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0019_merge_20251023_1630"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="annotations_assiette_detr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="DETR - Montant des dépenses éligibles retenues (en euros)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_assiette_dsil",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="DSIL - Montant des dépenses éligibles retenues (en euros)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_montant_accorde_detr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="DETR - Montant définitif de la subvention (en euros)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_montant_accorde_dsil",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="DSIL - Montant définitif de la subvention (en euros)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_taux_detr",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="DETR - Taux de subvention (%)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_taux_dsil",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=6,
                null=True,
                verbose_name="DSIL - Taux de subvention (%)",
            ),
        ),
    ]
