# Generated by Django 5.2.7 on 2025-11-17 15:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0020_demarche_updated_since"),
        (
            "gsl_demarches_simplifiees",
            "0020_dossier_annotations_assiette_detr_and_more",
        ),
    ]

    operations = []
