# Generated by Django 5.2.7 on 2025-12-03 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0011_alter_collegue_email"),
        ("gsl_demarches_simplifiees", "0021_merge_20251117_1647"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="annotations_champ_libre_2",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur 2"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_champ_libre_3",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur 3"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_date_ej_detr",
            field=models.DateField(
                blank=True, null=True, verbose_name="DETR - Date d'engagement juridique"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_date_ej_dsil",
            field=models.DateField(
                blank=True, null=True, verbose_name="DSIL - Date d'engagement juridique"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_acv",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet rattaché à un programme Action coeurs de Ville (ACV)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_autre_zonage_local",
            field=models.BooleanField(
                null=True, verbose_name="Projet rattaché à un autre zonage local"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_contrat_local",
            field=models.BooleanField(
                null=True, verbose_name="Projet rattaché à un contrat local"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_frr",
            field=models.BooleanField(null=True, verbose_name="Projet situé en FRR"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_pvd",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet rattaché à un programme Petites villes de demain (PVD)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_village_avenir",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet rattaché à un programme Villages d'avenir",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_numero_ej_detr",
            field=models.CharField(
                blank=True, verbose_name="DETR - N° engagement juridique"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_numero_ej_dsil",
            field=models.CharField(
                blank=True, verbose_name="DSIL - N° engagement juridique"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_quel_autre_zonage_local",
            field=models.CharField(blank=True, verbose_name="Précisez quel zonage."),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_quel_contrat_local",
            field=models.CharField(blank=True, verbose_name="Précisez quel contrat."),
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_montant_detr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="dont DETR",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_montant_dsil",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="dont DSIL",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_montant_xpf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant de l'aide demandée (en XPF)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_type_renouvellement",
            field=models.CharField(
                blank=True,
                verbose_name="Souhaitez-vous effectuer une nouvelle demande ou renouveler une demande précédente ?",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="finance_cout_total_xpf",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Coût total de l'opération (en XPF HT)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="projet_zonage_autre",
            field=models.CharField(
                blank=True, verbose_name="Autre zonage : précisez le nom du zonage"
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="annotations_champ_libre",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur 1"
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_autre_dsil_detr",
            field=models.BooleanField(
                null=True,
                verbose_name="Présentez-vous une autre opération au titre de la DETR/DSIL cette année ?",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_autres_aides",
            field=models.ManyToManyField(
                blank=True,
                to="gsl_demarches_simplifiees.autreaide",
                verbose_name="Comptez-vous solliciter d'autres aides publiques pour financer cette opération  ?",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_eligibilite_detr",
            field=models.ManyToManyField(
                blank=True,
                to="gsl_demarches_simplifiees.critereeligibilitedetr",
                verbose_name="Catégories prioritaires",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_eligibilite_dsil",
            field=models.ManyToManyField(
                blank=True,
                to="gsl_demarches_simplifiees.critereeligibilitedsil",
                verbose_name="DSIL · Éligibilité de l'opération",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant de l'aide demandée (en euros)",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_priorite_dsil_detr",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Si demandé par votre préfecture, précisez le niveau de priorité de ce dossier.",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_arrondissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_demarches_simplifiees.arrondissement",
                verbose_name="Arrondissement du demandeur",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_fonction",
            field=models.CharField(blank=True, verbose_name="Fonction"),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_nom",
            field=models.CharField(blank=True, verbose_name="Nom"),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_prenom",
            field=models.CharField(blank=True, verbose_name="Prénom"),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="projet_contractualisation_autre",
            field=models.CharField(
                blank=True, verbose_name="Autre contrat : précisez le nom du contrat"
            ),
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("label", models.CharField(unique=True, verbose_name="Libellé")),
                (
                    "core_arrondissement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ds_departements",
                        to="gsl_core.departement",
                        verbose_name="Département INSEE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département DS",
                "verbose_name_plural": "Départements DS",
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="porteur_de_projet_departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_demarches_simplifiees.departement",
                verbose_name="Département ou collectivité du demandeur",
            ),
        ),
    ]
