# Generated by Django 5.2.7 on 2025-12-05 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0011_alter_collegue_email"),
        ("gsl_demarches_simplifiees", "0021_merge_20251117_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_arrondissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_demarches_simplifiees.arrondissement",
                verbose_name="Arrondissement du demandeur",
            ),
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("label", models.CharField(unique=True, verbose_name="Libellé")),
                (
                    "core_departement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ds_departements",
                        to="gsl_core.departement",
                        verbose_name="Département INSEE",
                    ),
                ),
            ],
            options={
                "verbose_name": "Département DS",
                "verbose_name_plural": "Départements DS",
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="porteur_de_projet_departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_demarches_simplifiees.departement",
                verbose_name="Département ou collectivité du demandeur",
            ),
        ),
    ]
