# Generated by Django 5.2.8 on 2025-12-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0021_merge_20251117_1647"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="demande_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Montant de l'aide demandée (en euros)",
            ),
        ),
    ]
