# Generated by Django 5.2.8 on 2025-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0023_merge_20251216_1527"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_acv",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet rattaché à un programme Action coeurs de Ville (ACV)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_autre_zonage_local",
            field=models.BooleanField(
                null=True, verbose_name="Projet rattaché à un autre zonage local"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_contrat_local",
            field=models.BooleanField(
                null=True, verbose_name="Projet rattaché à un contrat local"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_frr",
            field=models.BooleanField(null=True, verbose_name="Projet situé en FRR"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_pvd",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet rattaché à un programme Petites villes de demain (PVD)",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_is_va",
            field=models.BooleanField(
                null=True,
                verbose_name="Projet rattaché à un programme Villages d'avenir",
            ),
        ),
    ]
