# Generated by Django 5.2.8 on 2025-12-17 16:46

import gsl_demarches_simplifiees.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0023_merge_20251216_1527"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldmappingforcomputer",
            name="django_field",
            field=models.CharField(
                blank=True,
                choices=gsl_demarches_simplifiees.models.mapping_field_choices,
                verbose_name="Champ Django",
            ),
        ),
    ]
