# Generated by Django 5.2.8 on 2026-01-05 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0024_alter_fieldmappingforcomputer_django_field",
        ),
        ("gsl_demarches_simplifiees", "0024_dossier_annotations_is_acv_and_more"),
    ]

    operations = []
