# Generated by Django 5.2.8 on 2026-01-08 14:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0025_merge_20260105_1749"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="ds_number",
            field=models.IntegerField(unique=True, verbose_name="Numéro DS"),
        ),
    ]
