# Generated by Django 5.2.8 on 2026-01-15 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0026_alter_dossier_ds_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="annotations_assiette",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="annotations_montant_accorde",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="annotations_taux",
        ),
    ]
