# Generated by Django 5.2.8 on 2026-01-16 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0027_remove_dossier_annotations_assiette_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demarche",
            name="perimetre",
        ),
    ]
