# Generated by Django 5.2.8 on 2026-01-16 16:10

import django.db.models.deletion
from django.db import migrations, models


def move_dossier_data(apps, schema_editor):
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    DossierData = apps.get_model("gsl_demarches_simplifiees", "DossierData")
    for dossier in Dossier.objects.iterator():
        dossier_data = DossierData.objects.create(
            ds_demarche=dossier.ds_demarche,
            raw_data=dossier.raw_ds_data,
            created_at=dossier.created_at,
            updated_at=dossier.updated_at,
        )
        dossier.ds_data = dossier_data
        dossier.ds_demarche_number = dossier.ds_demarche.ds_number
        dossier.save()


def restore_dossier_data(apps, schema_editor):
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    for dossier in Dossier.objects.all():
        if dossier.ds_data:
            dossier.raw_ds_data = dossier.ds_data.raw_data
            dossier.ds_demarche = dossier.ds_data.ds_demarche
            dossier.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0028_remove_demarche_perimetre"),
    ]

    operations = [
        migrations.CreateModel(
            name="DossierData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "ds_demarche",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_demarches_simplifiees.demarche",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Données DS brutes"
                    ),
                ),
            ],
            options={
                "verbose_name": "Données de dossier DN",
                "verbose_name_plural": "Données de dossiers DN",
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="ds_demarche_number",
            field=models.IntegerField(null=True, verbose_name="Numéro de la démarche"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="ds_data",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.dossierdata",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="ds_demarche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_demarches_simplifiees.demarche",
                null=True,
            ),
        ),  # Needed for the reverse data migration to function, so when the field is created back it is nullable
        migrations.RunPython(move_dossier_data, reverse_code=restore_dossier_data),
        migrations.RemoveField(
            model_name="dossier",
            name="raw_ds_data",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="ds_demarche",
        ),
        migrations.AlterField(
            model_name="dossier",
            name="ds_demarche_number",
            field=models.IntegerField(verbose_name="Numéro de la démarche"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dossier",
            name="ds_data",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_demarches_simplifiees.dossierdata",
            ),
        ),
        migrations.AlterField(
            model_name="dossierdata",
            name="ds_demarche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_demarches_simplifiees.demarche",
            ),
        ),
    ]
