# Generated by Django 5.2.8 on 2026-01-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0029_separation_dossier_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="annotations_autre_zonage_local",
            field=models.CharField(blank=True, verbose_name="Zonage local"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_contrat_local",
            field=models.CharField(blank=True, verbose_name="Contrat local"),
        ),
    ]
