# Generated by Django 5.2.8 on 2026-01-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0030_dossier_annotations_autre_zonage_local_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="projet_zonage_autre",
            field=models.CharField(
                blank=True, verbose_name="Autre zonage : précisez le nom du zonage"
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="projet_contractualisation_autre",
            field=models.CharField(
                blank=True, verbose_name="Autre contrat : précisez le nom du contrat"
            ),
        ),
    ]
