# Generated by Django 5.2.8 on 2026-01-23 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0030_dossier_annotations_autre_zonage_local_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieDsil",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("label", models.CharField(verbose_name="Libellé")),
                ("rank", models.IntegerField(null=True, verbose_name="Rang")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de désactivation"
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_demarches_simplifiees.demarche",
                        verbose_name="Démarche",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie DSIL",
                "verbose_name_plural": "Catégories DSIL",
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_categorie_dsil",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.categoriedsil",
                verbose_name="DSIL · Éligibilité de l'opération",
            ),
        ),
    ]
