# Generated by Django 5.2.8 on 2026-01-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0031_dossier_projet_zonage_autre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="demande_annee_precedente",
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_renouvellement",
            field=models.CharField(
                blank=True,
                verbose_name="Souhaitez-vous effectuer une nouvelle demande ou renouveler une demande précédente ?",
            ),
        ),
    ]
