# Generated by Django 5.2.8 on 2026-01-27 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0031_categoriedsil_dossier_demande_categorie_dsil",
        ),
        ("gsl_demarches_simplifiees", "0031_dossier_projet_zonage_autre_and_more"),
    ]

    operations = []
