# Generated by Django 5.2.8 on 2026-01-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0031_dossier_projet_zonage_autre_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="annotations_champ_libre",
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_champ_libre_1",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur 1"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_champ_libre_2",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur 2"
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="annotations_champ_libre_3",
            field=models.TextField(
                blank=True, verbose_name="Champ libre pour le service instructeur 3"
            ),
        ),
    ]
