# Generated by Django 5.2.8 on 2026-01-30 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0032_remove_dossier_annotations_champ_libre_and_more",
        ),
        (
            "gsl_demarches_simplifiees",
            "0032_remove_dossier_demande_annee_precedente_and_more",
        ),
    ]

    operations = []
