# Generated by Django 5.2.8 on 2026-01-27 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0012_departement_active"),
        ("gsl_demarches_simplifiees", "0032_merge_20260127_0751"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategorieDetr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("label", models.CharField(verbose_name="Libellé")),
                ("rank", models.IntegerField(null=True, verbose_name="Rang")),
                ("active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "deactivated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de désactivation"
                    ),
                ),
                (
                    "parent_label",
                    models.CharField(
                        blank=True, verbose_name="Libellé de la catégorie parente"
                    ),
                ),
                (
                    "demarche",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_demarches_simplifiees.demarche",
                        verbose_name="Démarche",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="categories_detr",
                        to="gsl_core.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie DETR",
                "verbose_name_plural": "Catégories DETR",
            },
        ),
    ]
