# Generated by Django 5.2.8 on 2026-01-30 14:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0032_merge_20260127_0751"),
        ("gsl_demarches_simplifiees", "0033_merge_20260130_1455"),
    ]

    operations = []
