# Generated by Django 5.2.8 on 2026-01-27 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0033_categoriedetr"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="demande_categorie_detr",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.categoriedetr",
                verbose_name="Catégories prioritaires",
            ),
        ),
    ]
