# Generated by Django 5.2.8 on 2026-01-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0012_departement_active"),
        ("gsl_demarches_simplifiees", "0034_dossier_demande_categorie_detr"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="categoriedetr",
            constraint=models.UniqueConstraint(
                fields=("label", "demarche", "departement"),
                name="unique_categorie_detr_label_per_demarche_departement",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriedsil",
            constraint=models.UniqueConstraint(
                fields=("label", "demarche"),
                name="unique_categorie_dsil_label_per_demarche",
                nulls_distinct=False,
            ),
        ),
    ]
