# Generated by Django 5.2.8 on 2026-01-28 11:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0035_categoriedetr_unique_categorie_detr_label_per_demarche_departement_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="demande_eligibilite_detr",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="demande_eligibilite_dsil",
        ),
        migrations.DeleteModel(
            name="CritereEligibiliteDetr",
        ),
        migrations.DeleteModel(
            name="CritereEligibiliteDsil",
        ),
    ]
