# Generated by Django 5.2.8 on 2026-01-28 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0036_remove_dossier_demande_eligibilite_detr_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fieldmappingforcomputer",
            name="field_mapping_for_human",
        ),
        migrations.DeleteModel(
            name="FieldMappingForHuman",
        ),
    ]
