# Generated by Django 5.2.8 on 2026-01-30 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0034_merge_20260130_1504"),
        (
            "gsl_demarches_simplifiees",
            "0036_remove_dossier_demande_eligibilite_detr_and_more",
        ),
    ]

    operations = []
