# Generated by Django 5.2.8 on 2026-01-28 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0037_remove_fieldmappingforcomputer_field_mapping_for_human_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FieldMappingForComputer",
            new_name="FieldMapping",
        ),
        migrations.AlterModelOptions(
            name="fieldmapping",
            options={
                "verbose_name": "Correspondance de champ",
                "verbose_name_plural": "Correspondances de champ",
            },
        ),
    ]
