# Generated by Django 5.2.8 on 2026-01-30 11:55

import django.db.models.deletion
from django.db import migrations, models


def set_arrondissement_and_departement_to_null(apps, schema_editor):
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    for dossier in Dossier.objects.all():
        dossier.porteur_de_projet_arrondissement = None
        dossier.porteur_de_projet_departement = None
        dossier.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0012_departement_active"),
        (
            "gsl_demarches_simplifiees",
            "0038_rename_fieldmappingforcomputer_fieldmapping_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(
            set_arrondissement_and_departement_to_null,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_arrondissement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_core.arrondissement",
                verbose_name="Arrondissement du demandeur",
            ),
        ),
        migrations.RemoveField(
            model_name="departement",
            name="core_departement",
        ),
        migrations.AlterField(
            model_name="dossier",
            name="porteur_de_projet_departement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_core.departement",
                verbose_name="Département ou collectivité du demandeur",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="perimetre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.perimetre",
            ),
        ),
        migrations.DeleteModel(
            name="Arrondissement",
        ),
        migrations.DeleteModel(
            name="Departement",
        ),
        migrations.RunPython(
            migrations.RunPython.noop,
            reverse_code=set_arrondissement_and_departement_to_null,
        ),
    ]
