# Generated by Django 5.2.8 on 2026-01-30 14:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0037_merge_20260130_1511"),
        (
            "gsl_demarches_simplifiees",
            "0038_rename_fieldmappingforcomputer_fieldmapping_and_more",
        ),
    ]

    operations = []
