# Generated by Django 5.2.8 on 2026-01-30 14:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0039_alter_dossier_porteur_de_projet_arrondissement_and_more",
        ),
        ("gsl_demarches_simplifiees", "0039_merge_20260130_1528"),
    ]

    operations = []
