# Generated by Django 5.2.8 on 2026-01-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0039_merge_20260130_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="demande_categorie_detr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.categoriedetr",
                verbose_name="Catégories prioritaires",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_categorie_dsil",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.categoriedsil",
                verbose_name="DSIL · Éligibilité de l'opération",
            ),
        ),
    ]
