# Generated by Django 5.2.8 on 2026-02-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0040_alter_dossier_demande_categorie_detr_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="demande_has_categorie_detr",
            field=models.BooleanField(
                blank=True,
                null=True,
                verbose_name="DETR · Le projet s'inscrit-il dans une des catégories prioritaires définies par la commission départementale d'élus ?",
            ),
        ),
    ]
