# Generated by Django 5.2.8 on 2026-02-02 11:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0040_alter_dossier_demande_categorie_detr_and_more",
        ),
        ("gsl_demarches_simplifiees", "0040_merge_20260130_1556"),
    ]

    operations = []
