# Generated by Django 5.2.8 on 2026-02-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0041_dossier_demande_has_categorie_detr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="annotations_taux_detr",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="DETR - Taux de subvention (%)",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="annotations_taux_dsil",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=12,
                null=True,
                verbose_name="DSIL - Taux de subvention (%)",
            ),
        ),
    ]
