# Generated by Django 5.2.8 on 2026-02-09 18:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0041_merge_20260202_1216"),
        (
            "gsl_demarches_simplifiees",
            "0042_alter_dossier_annotations_taux_detr_and_more",
        ),
    ]

    operations = []
