# Generated by Django 5.2.8 on 2026-02-09 18:10

from django.db import migrations
from django.db.models import F, OuterRef
from django.db.models.expressions import Subquery

from gsl_demarches_simplifiees.importer.utils import get_perimetre_from_dossier


def set_perimetre_to_dossier(apps, schema_editor):
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    Dossier.objects.all().update(
        perimetre=Subquery(
            Dossier.objects.filter(pk=OuterRef("pk")).values("projet__perimetre")[:1]
        )
    )
    for dossier in Dossier.objects.filter(perimetre__isnull=True).iterator():
        dossier.perimetre = get_perimetre_from_dossier(dossier)
        dossier.save()


def set_perimetre_to_projet(apps, schema_editor):
    Projet = apps.get_model("gsl_projet", "Projet")
    Projet.objects.all().update(
        perimetre=Subquery(
            Projet.objects.filter(pk=OuterRef("pk")).values("dossier_ds__perimetre")[:1]
        )
    )


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0043_merge_20260209_1908"),
    ]

    operations = [
        migrations.RunPython(
            set_perimetre_to_dossier, reverse_code=set_perimetre_to_projet
        ),
    ]
