# Generated by Django 5.2.8 on 2026-02-18 14:53

import django.db.models.deletion
from django.db import migrations, models


def set_ds_demarche_to_dossier(apps, schema_editor):
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    Dossier.objects.all().update(
        ds_demarche=models.Subquery(
            Dossier.objects.filter(id=models.OuterRef("id")).values(
                "ds_data__ds_demarche"
            )[:1]
        )
    )


def set_ds_demarche_to_dossier_data(apps, schema_editor):
    DossierData = apps.get_model("gsl_demarches_simplifiees", "DossierData")
    Demarche = apps.get_model("gsl_demarches_simplifiees", "Demarche")
    demarche = Demarche.objects.first()
    DossierData.objects.all().update(ds_demarche=demarche)


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0044_associate_perimetre_to_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="ds_demarche",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.demarche",
            ),
        ),
        migrations.RunPython(
            set_ds_demarche_to_dossier,
            reverse_code=set_ds_demarche_to_dossier_data,
        ),
        migrations.RemoveField(
            model_name="dossierdata",
            name="ds_demarche",
        ),
    ]
