# Generated by Django 5.2.8 on 2026-02-18 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0045_remove_dossierdata_ds_demarche_dossier_ds_demarche_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="ds_demarche_number",
        ),
    ]
