# Generated by Django 5.2.8 on 2026-02-20 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0046_remove_dossier_ds_demarche_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossier",
            name="ds_demarche",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_demarches_simplifiees.demarche",
            ),
        ),
    ]
