# Generated by Django 5.2.8 on 2026-02-20

import django.db.models.deletion
from django.db import migrations, models


def set_dossier_on_dossier_data(apps, schema_editor):
    """Set DossierData.dossier from the current Dossier.ds_data relation."""
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    DossierData = apps.get_model("gsl_demarches_simplifiees", "DossierData")
    for dossier in Dossier.objects.iterator():
        # Current relation: Dossier has ds_data_id -> DossierData
        dossier_data_id = dossier.ds_data_id
        if dossier_data_id is not None:
            DossierData.objects.filter(pk=dossier_data_id).update(dossier_id=dossier.pk)


def unset_dossier_on_dossier_data(apps, schema_editor):
    """Reverse: restore Dossier.ds_data_id from DossierData.dossier_id."""
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    DossierData = apps.get_model("gsl_demarches_simplifiees", "DossierData")
    for dossier_data in DossierData.objects.iterator():
        if dossier_data.dossier_id is not None:
            Dossier.objects.filter(pk=dossier_data.dossier_id).update(
                ds_data_id=dossier_data.pk
            )


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0047_alter_dossier_ds_demarche"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierdata",
            name="dossier",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ds_data",
                to="gsl_demarches_simplifiees.dossier",
                verbose_name="Dossier",
            ),
        ),
        migrations.RunPython(
            set_dossier_on_dossier_data, unset_dossier_on_dossier_data
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="ds_data",
        ),
        migrations.AlterField(
            model_name="dossierdata",
            name="dossier",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ds_data",
                to="gsl_demarches_simplifiees.dossier",
                verbose_name="Dossier",
            ),
        ),
    ]
