# Generated by Django 5.2.8 on 2026-03-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0048_move_dossier_relation_to_dossierdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="demarche",
            name="sync_cursor",
            field=models.TextField(
                blank=True, default="", verbose_name="Curseur de synchronisation DS"
            ),
        ),
        migrations.AlterField(
            model_name="demarche",
            name="updated_since",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Valeur pour le curseur de synchronisation DS",
            ),
        ),
    ]
