# Generated by Django 5.2.8 on 2026-03-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0048_move_dossier_relation_to_dossierdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="demarche",
            name="sync_cursor",
            field=models.CharField(
                blank=True,
                default="",
                max_length=255,
                verbose_name="Curseur de synchronisation DS",
            ),
        ),
    ]
