# Generated by Django 6.0.3 on 2026-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0049_demarche_sync_cursor_alter_demarche_updated_since",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Cofinancement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("label", models.CharField(unique=True, verbose_name="Libellé")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_autre",
            field=models.TextField(
                blank=True,
                verbose_name="Autre dispositif de financement - Précisez le dispositif concerné",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_autre_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Autre dispositif de financement - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_conseil_departemental_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Aide du Conseil départemental  - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_conseil_regional_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Aide du Conseil régional - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_dpv_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="DPV - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_epci_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Aide d'un EPCI - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_fnadt_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="FNADT - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_fonds_vert_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Fonds vert - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="cofinancement_ue_montant",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Aide de l'Union européenne - Précisez le montant sollicité ou obtenu",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_autres_aides",
            field=models.ManyToManyField(
                blank=True,
                to="gsl_demarches_simplifiees.autreaide",
                verbose_name="Comptez-vous solliciter d'autres aides publiques pour financer cette opération ?",
            ),
        ),
        migrations.AddField(
            model_name="dossier",
            name="demande_cofinancements",
            field=models.ManyToManyField(
                blank=True,
                to="gsl_demarches_simplifiees.cofinancement",
                verbose_name="Comptez-vous solliciter d'autres aides publiques pour financer cette opération  ?",
            ),
        ),
    ]
