# Generated by Django 6.0.3 on 2026-03-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0049_demarche_sync_cursor_alter_demarche_updated_since",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="porteur_de_projet_epci",
            field=models.CharField(
                blank=True,
                verbose_name="EPCI à fiscalité propre dont est membre la commune",
            ),
        ),
    ]
