# Generated by Django 6.0.3 on 2026-03-24 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0050_add_porteur_de_projet_epci_to_dossier"),
        ("gsl_demarches_simplifiees", "0050_cofinancement"),
    ]

    operations = []
