# Generated by Django 6.0.3 on 2026-03-18 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0050_cofinancement"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="demande_autres_aides",
        ),
        migrations.DeleteModel(
            name="AutreAide",
        ),
    ]
