# Generated by Django 6.0.3 on 2026-03-27 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0051_merge_20260324_1235"),
        (
            "gsl_demarches_simplifiees",
            "0051_remove_dossier_demande_autres_aides_delete_autreaide",
        ),
    ]

    operations = []
