# Generated by Django 6.0.3 on 2026-03-27 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0052_merge_20260324_1406"),
        ("gsl_demarches_simplifiees", "0052_merge_20260327_1130"),
    ]

    operations = []
