# Generated by Django 6.0.3 on 2026-04-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0053_merge_20260327_1201"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="porteur_de_projet_civilite",
            field=models.CharField(
                blank=True, verbose_name="Civilité du porteur de projet"
            ),
        ),
    ]
