# Generated by Django 6.0.3 on 2026-04-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0054_add_porteur_de_projet_civilite_to_dossier"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dossier",
            name="demande_autre_numero_dossier",
        ),
        migrations.RemoveField(
            model_name="dossier",
            name="demande_autre_precision",
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_autre_dsil_detr",
            field=models.BooleanField(
                null=True,
                verbose_name="Présentez-vous une autre opération au titre de la DETR/DSIL cette année ?",
            ),
        ),
        migrations.AlterField(
            model_name="dossier",
            name="demande_priorite_dsil_detr",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Si demandé par votre préfecture, précisez le niveau de priorité de ce dossier.",
            ),
        ),
    ]
