# Generated by Django 6.0.3 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0054_add_porteur_de_projet_civilite_to_dossier"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldmapping",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="fieldmapping",
            name="deactivated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Désactivé le"
            ),
        ),
    ]
