# Generated by Django 6.0.3 on 2026-04-27 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0055_fieldmapping_is_active_deactivated_at"),
        (
            "gsl_demarches_simplifiees",
            "0055_remove_dossier_demande_autre_numero_dossier_and_more",
        ),
    ]

    operations = []
