# Generated by Django 6.0.3 on 2026-04-22 09:26

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0055_fieldmapping_is_active_deactivated_at"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="fieldmapping",
            managers=[
                ("actives", django.db.models.manager.Manager()),
            ],
        ),
    ]
