# Generated by Django 6.0.3 on 2026-05-13 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0057_pg_trgm_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossier",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Actif"),
        ),
        migrations.AddField(
            model_name="dossier",
            name="raison_desactivation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("archive", "Archivé"),
                    ("corbeille", "Dans la corbeille"),
                    ("supprime", "Supprimé"),
                ],
                default="",
                max_length=50,
                verbose_name="Raison de désactivation",
            ),
        ),
    ]
