# Generated by Django 6.0.3 on 2026-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_demarches_simplifiees",
            "0058_dossier_is_active_dossier_raison_desactivation",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="demarche",
            name="deleted_cursor",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Curseur de synchronisation des dossiers supprimés",
            ),
        ),
        migrations.AddField(
            model_name="demarche",
            name="pending_deleted_cursor",
            field=models.TextField(
                blank=True,
                default="",
                verbose_name="Curseur de synchronisation des dossiers en attente de suppression",
            ),
        ),
    ]
