# Generated by Django 6.0.8 on 2026-10-09 08:51

from django.db import migrations, models


def reactivate_archived_dossiers(apps, schema_editor):
    """
    L'archivage sur DN ne désactive plus les dossiers dans Turgot : on
    réactive ceux qui avaient été désactivés pour cette raison.
    """
    Dossier = apps.get_model("gsl_demarches_simplifiees", "Dossier")
    Dossier.objects.filter(raison_desactivation="archive").update(
        is_active=True, raison_desactivation=""
    )


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_demarches_simplifiees", "0059_compute_personnemorale_siren"),
    ]

    operations = [
        migrations.RunPython(
            reactivate_archived_dossiers,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="dossier",
            name="raison_desactivation",
            field=models.CharField(
                blank=True,
                choices=[("corbeille", "Dans la corbeille"), ("supprime", "Supprimé")],
                default="",
                max_length=50,
                verbose_name="Raison de désactivation",
            ),
        ),
    ]
