from typing import Literal

DOTATION_DETR = "DETR"
DOTATION_DSIL = "DSIL"
DOTATIONS = (DOTATION_DETR, DOTATION_DSIL)
DOTATION_CHOICES = ((DOTATION_DETR, DOTATION_DETR), (DOTATION_DSIL, DOTATION_DSIL))

# TYPE
POSSIBLE_DOTATIONS = Literal["DETR", "DSIL"]

PROJET_STATUS_ACCEPTED = "accepted"
PROJET_STATUS_REFUSED = "refused"
PROJET_STATUS_PROCESSING = "processing"
PROJET_STATUS_DISMISSED = "dismissed"
PROJET_STATUS_CHOICES = (
    (PROJET_STATUS_ACCEPTED, "✅ Accepté"),
    (PROJET_STATUS_REFUSED, "❌ Refusé"),
    (PROJET_STATUS_PROCESSING, "🔄 En traitement"),
    (PROJET_STATUS_DISMISSED, "⛔️ Classé sans suite"),
)

ARRETE = "arrete"
LETTRE = "lettre"
POSSIBLE_DOCUMENTS = Literal["arrete", "lettre"]

MIN_DEMANDE_MONTANT_FOR_AVIS_DETR = 100_000
