# Generated by Django 5.2.2 on 2025-06-13 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArreteSigne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="arrete_signe/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "programmation_projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_programmation.programmationprojet",
                    ),
                ),
            ],
        ),
    ]
