# Generated by Django 5.2.2 on 2025-06-17 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0001_initial"),
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arretesigne",
            name="programmation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_programmation.programmationprojet",
            ),
        ),
    ]
