# Generated by Django 5.2.2 on 2025-06-17 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0002_alter_arretesigne_programmation_projet"),
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arretesigne",
            name="programmation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrete_signe",
                to="gsl_programmation.programmationprojet",
            ),
        ),
    ]
