# Generated by Django 5.2.3 on 2025-06-25 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0002_rename_uploaded_at_arretesigne_created_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="arretesigne",
            options={
                "verbose_name": "Arrêté signé",
                "verbose_name_plural": "Arrêtés signés",
            },
        ),
    ]
