# Generated by Django 5.2.3 on 2025-06-27 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0003_alter_arretesigne_options"),
        ("gsl_notification", "0003_alter_arretesigne_options_arrete"),
    ]

    operations = []
