# Generated by Django 5.2.2 on 2025-06-17 19:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0003_alter_arretesigne_programmation_projet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arretesigne",
            name="name",
        ),
    ]
