# Generated by Django 5.2.4 on 2025-07-15 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_notification", "0005_alter_arrete_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModeleArrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Exemple : “Modèle d’arrêté DSIL 2025”",
                        verbose_name="Nom du modèle",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Cette description apparaîtra en dessous du titre dans la liste des modèles, elle permet de vous aider à distinguer vos modèles",
                        verbose_name="Description du modèle",
                    ),
                ),
                (
                    "dotation",
                    models.CharField(
                        choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                        verbose_name="Dotation",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                        upload_to="",
                        verbose_name="Logo situé en haut à gauche",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        help_text="Reprenez le texte contenu dans l’image du logo",
                        verbose_name="Texte alternatif du logo",
                    ),
                ),
                (
                    "top_right_text",
                    models.TextField(
                        help_text="Affiché en haut à droite de la première page",
                        verbose_name="Texte situé en haut à droite",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenu HTML de l'arrêté, utilisé pour les exports.",
                        verbose_name="Contenu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modeles_arrete",
                        to="gsl_core.perimetre",
                        verbose_name="Périmètre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle d’arrêté",
                "verbose_name_plural": "Modèles d’arrêté",
            },
        ),
    ]
