# Generated by Django 5.2.4 on 2025-07-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0006_modelearrete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelearrete",
            name="logo",
            field=models.FileField(
                help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                upload_to="",
                verbose_name="Logo situé en haut à gauche",
            ),
        ),
    ]
