# Generated by Django 5.2.4 on 2025-07-23 10:29

import gsl_notification.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0007_arrete_modele"),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelearrete",
            name="logo",
            field=models.FileField(
                help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                upload_to=gsl_notification.models.tokenized_file_in_timestamped_folder,
                verbose_name="Logo situé en haut à gauche",
            ),
        ),
    ]
