# Generated by Django 5.2.4 on 2025-08-05 08:54

import django.db.models.deletion
import gsl_notification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_notification", "0008_alter_modelearrete_logo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelearrete",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu HTML du modèle.",
                verbose_name="Contenu",
            ),
        ),
        migrations.AlterField(
            model_name="modelearrete",
            name="name",
            field=models.CharField(
                help_text="Exemple : “Modèle DSIL 2025”", verbose_name="Nom du modèle"
            ),
        ),
        migrations.CreateModel(
            name="ModeleLettreNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Exemple : “Modèle DSIL 2025”",
                        verbose_name="Nom du modèle",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Cette description apparaîtra en dessous du titre dans la liste des modèles, elle permet de vous aider à distinguer vos modèles",
                        verbose_name="Description du modèle",
                    ),
                ),
                (
                    "dotation",
                    models.CharField(
                        choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                        verbose_name="Dotation",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                        upload_to=gsl_notification.models.tokenized_file_in_timestamped_folder,
                        verbose_name="Logo situé en haut à gauche",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        help_text="Reprenez le texte contenu dans l’image du logo",
                        verbose_name="Texte alternatif du logo",
                    ),
                ),
                (
                    "top_right_text",
                    models.TextField(
                        help_text="Affiché en haut à droite de la première page",
                        verbose_name="Texte situé en haut à droite",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenu HTML du modèle.",
                        verbose_name="Contenu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modeles_lettre_notification",
                        to="gsl_core.perimetre",
                        verbose_name="Périmètre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de lettre de notification",
                "verbose_name_plural": "Modèles de lettre de notification",
            },
        ),
    ]
