# Generated by Django 5.2.4 on 2025-08-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_notification",
            "0009_alter_modelearrete_content_alter_modelearrete_name_and_more",
        ),
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrete",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu HTML du document, utilisé pour les exports.",
                verbose_name="Contenu du document",
            ),
        ),
        migrations.CreateModel(
            name="LettreNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenu HTML du document, utilisé pour les exports.",
                        verbose_name="Contenu du document",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_notification.modelelettrenotification",
                    ),
                ),
                (
                    "programmation_projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lettre_notification",
                        to="gsl_programmation.programmationprojet",
                        verbose_name="Programmation projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettre de notification",
                "verbose_name_plural": "Lettres de notification",
            },
        ),
    ]
