# Generated by Django 5.2.4 on 2025-08-13 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0011_annexe"),
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArreteEtLettreSignes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("file", models.FileField(upload_to="arrete_et_lettre_signes/")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programmation_projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrete_et_lettre_signes",
                        to="gsl_programmation.programmationprojet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrêté et lettre signés",
                "verbose_name_plural": "Arrêtés et lettres signés",
            },
        ),
        migrations.DeleteModel(
            name="ArreteSigne",
        ),
    ]
