# Generated by Django 5.2.8 on 2025-11-28 15:21

import django.db.models.deletion
from django.db import migrations, models


def set_documents_projet_and_dotation(apps, schema_editor):
    Arrete = apps.get_model("gsl_notification", "Arrete")
    LettreNotification = apps.get_model("gsl_notification", "LettreNotification")
    ArreteEtLettreSignes = apps.get_model("gsl_notification", "ArreteEtLettreSignes")
    Annexe = apps.get_model("gsl_notification", "Annexe")

    for model in [Arrete, LettreNotification, ArreteEtLettreSignes, Annexe]:
        for doc in model.objects.all():
            doc.projet = doc.programmation_projet.dotation_projet.projet
            if model is not Annexe:
                doc.dotation = doc.programmation_projet.dotation_projet.dotation

            doc.save(update_fields=["projet", "dotation"])


def set_documents_programmation_projet(apps, schema_editor):
    Arrete = apps.get_model("gsl_notification", "Arrete")
    LettreNotification = apps.get_model("gsl_notification", "LettreNotification")
    ArreteEtLettreSignes = apps.get_model("gsl_notification", "ArreteEtLettreSignes")
    DotationProjet = apps.get_model("gsl_projet", "DotationProjet")
    ProgrammationProjet = apps.get_model("gsl_programmation", "ProgrammationProjet")

    for model in [Arrete, LettreNotification, ArreteEtLettreSignes]:
        for doc in model.objects.all():
            dotation_projet = DotationProjet.objects.get(
                projet=doc.projet, dotation=doc.dotation
            )
            programmation_projet = ProgrammationProjet.objects.get(
                dotation_projet=dotation_projet
            )
            doc.programmation_projet = programmation_projet
            doc.save(update_fields=["programmation_projet"])

    Annexe = apps.get_model("gsl_notification", "Annexe")
    for annexe in Annexe.objects.all():
        programmation_projet = ProgrammationProjet.objects.filter(
            dotation_projet__projet=annexe.projet
        ).first()
        annexe.programmation_projet = programmation_projet
        annexe.save()


def remove_duplicated_demandeurs(apps, schema_editor):
    Demandeur = apps.get_model("gsl_projet", "Demandeur")
    Projet = apps.get_model("gsl_projet", "Projet")

    for siret_dict in (
        Demandeur.objects.values("siret")
        .annotate(Count("siret"))
        .filter(siret__count__gt=1)
    ):
        siret = siret_dict["siret"]
        first_demandeur = Demandeur.objects.filter(siret=siret).first()
        for projet in Projet.objects.filter(demandeur__siret=siret):
            projet.demandeur = first_demandeur
            projet.save()
        for other_demandeur in Demandeur.objects.filter(siret=siret).exclude(
            id=first_demandeur.id
        ):
            other_demandeur.delete()


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_notification",
            "0013_alter_annexe_file_alter_arreteetlettresignes_file_and_more",
        ),
        ("gsl_projet", "0025_projet_notified_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="annexe",
            name="projet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annexes",
                to="gsl_projet.projet",
            ),
        ),
        migrations.AddField(
            model_name="arrete",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                default="DETR",
                verbose_name="Dotation",
            ),
        ),
        migrations.AddField(
            model_name="arrete",
            name="projet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arretes",
                to="gsl_projet.projet",
                verbose_name="Projet",
            ),
        ),
        migrations.AddField(
            model_name="arreteetlettresignes",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                default="DETR",
                verbose_name="Dotation",
            ),
        ),
        migrations.AddField(
            model_name="arreteetlettresignes",
            name="projet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrete_et_lettre_signes",
                to="gsl_projet.projet",
            ),
        ),
        migrations.AddField(
            model_name="lettrenotification",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                default="DETR",
                verbose_name="Dotation",
            ),
        ),
        migrations.AddField(
            model_name="lettrenotification",
            name="projet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lettres_notification",
                to="gsl_projet.projet",
                verbose_name="Projet",
            ),
        ),
        migrations.RunPython(
            set_documents_projet_and_dotation, set_documents_programmation_projet
        ),
        migrations.RemoveField(
            model_name="annexe",
            name="programmation_projet",
        ),
        migrations.RemoveField(
            model_name="arrete",
            name="programmation_projet",
        ),
        migrations.RemoveField(
            model_name="arreteetlettresignes",
            name="programmation_projet",
        ),
        migrations.RemoveField(
            model_name="lettrenotification",
            name="programmation_projet",
        ),
    ]


# TODO : rollback doesn't works : django.db.utils.IntegrityError: column "programmation_projet_id" of relation "gsl_notification_lettrenotification" contains null values
