# Generated by Django 5.2.11 on 2026-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0014_arrete_size_lettrenotification_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="annexe",
            name="is_infected",
            field=models.BooleanField(null=True, verbose_name="Fichier infecté"),
        ),
        migrations.AddField(
            model_name="annexe",
            name="last_scan",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière analyse antivirus"
            ),
        ),
        migrations.AddField(
            model_name="arreteetlettresignes",
            name="is_infected",
            field=models.BooleanField(null=True, verbose_name="Fichier infecté"),
        ),
        migrations.AddField(
            model_name="arreteetlettresignes",
            name="last_scan",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière analyse antivirus"
            ),
        ),
    ]
