# Generated by Django 5.2.8 on 2025-11-28 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0014_remove_annexe_programmation_projet_and_more"),
        ("gsl_projet", "0025_projet_notified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annexe",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annexes",
                to="gsl_projet.projet",
            ),
        ),
        migrations.AlterField(
            model_name="arrete",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")], verbose_name="Dotation"
            ),
        ),
        migrations.AlterField(
            model_name="arrete",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arretes",
                to="gsl_projet.projet",
                verbose_name="Projet",
            ),
        ),
        migrations.AlterField(
            model_name="arreteetlettresignes",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")], verbose_name="Dotation"
            ),
        ),
        migrations.AlterField(
            model_name="arreteetlettresignes",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="arrete_et_lettre_signes",
                to="gsl_projet.projet",
            ),
        ),
        migrations.AlterField(
            model_name="lettrenotification",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")], verbose_name="Dotation"
            ),
        ),
        migrations.AlterField(
            model_name="lettrenotification",
            name="projet",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lettres_notification",
                to="gsl_projet.projet",
                verbose_name="Projet",
            ),
        ),
    ]
