# Generated by Django 5.2.8 on 2025-11-28 16:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0015_alter_annexe_projet_alter_arrete_dotation_and_more"),
        ("gsl_projet", "0025_projet_notified_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="arrete",
            constraint=models.UniqueConstraint(
                fields=("projet", "dotation"),
                name="unicity_by_arrete_projet_and_dotation",
            ),
        ),
        migrations.AddConstraint(
            model_name="arreteetlettresignes",
            constraint=models.UniqueConstraint(
                fields=("projet", "dotation"),
                name="unicity_by_arrete_and_lettre_signes_projet_and_dotation",
            ),
        ),
        migrations.AddConstraint(
            model_name="lettrenotification",
            constraint=models.UniqueConstraint(
                fields=("projet", "dotation"),
                name="unicity_by_lettre_projet_and_dotation",
            ),
        ),
    ]
