# Generated by Django 6.0.5 on 2026-06-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0020_exportjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("arrete", "Arrêté"),
                    ("lettre", "Lettre de notification"),
                    ("arrete_et_lettre", "Arrêté et lettre"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="exportjob",
            name="export_format",
            field=models.CharField(
                choices=[
                    ("un_pdf_par_document", "Un PDF par document"),
                    ("un_seul_pdf_ensemble", "Un seul PDF pour l'ensemble"),
                    ("un_pdf_par_projet", "Un PDF par projet"),
                    ("un_seul_pdf_groupe_par_projet", "Un seul PDF groupé par projet"),
                ],
                max_length=64,
            ),
        ),
    ]
