# Generated by Django 6.0.5 on 2026-07-08 07:05

import django.db.models.deletion
import gsl_notification.models
import gsl_notification.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0016_alter_departement_active"),
        ("gsl_notification", "0020_exportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="modelearrete",
            name="perimetre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modeles_%(class)s",
                to="gsl_core.perimetre",
                verbose_name="Périmètre",
            ),
        ),
        migrations.AlterField(
            model_name="modelelettrenotification",
            name="perimetre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="modeles_%(class)s",
                to="gsl_core.perimetre",
                verbose_name="Périmètre",
            ),
        ),
        migrations.CreateModel(
            name="ModeleLettreRefus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Exemple : “Modèle DSIL 2025”",
                        verbose_name="Nom du modèle",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Cette description apparaîtra en dessous du titre dans la liste des modèles, elle permet de vous aider à distinguer vos modèles",
                        verbose_name="Description du modèle",
                    ),
                ),
                (
                    "dotation",
                    models.CharField(
                        choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                        verbose_name="Dotation",
                    ),
                ),
                (
                    "logo",
                    models.FileField(
                        help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                        upload_to=gsl_notification.models.tokenized_file_in_timestamped_folder,
                        validators=[gsl_notification.validators.logo_file_validator],
                        verbose_name="Logo situé en haut à gauche",
                    ),
                ),
                (
                    "logo_alt_text",
                    models.CharField(
                        help_text="Reprenez le texte contenu dans l’image du logo",
                        verbose_name="Texte alternatif du logo",
                    ),
                ),
                (
                    "top_right_text",
                    models.TextField(
                        help_text="Affiché en haut à droite de la première page",
                        verbose_name="Texte situé en haut à droite",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenu HTML du modèle.",
                        verbose_name="Contenu",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_scan",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière analyse antivirus"
                    ),
                ),
                (
                    "is_infected",
                    models.BooleanField(null=True, verbose_name="Fichier infecté"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "perimetre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="modeles_%(class)s",
                        to="gsl_core.perimetre",
                        verbose_name="Périmètre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Modèle de lettre de refus ou classement sans suite",
                "verbose_name_plural": "Modèles de lettre de refus ou classement sans suite",
            },
        ),
    ]
