# Generated by Django 6.0.5 on 2026-07-31 10:32

import django.db.models.deletion
import gsl_notification.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0022_alter_lettrenotification_programmation_projet"),
        ("gsl_programmation", "0026_add_min_value_validator_to_enveloppe_montant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrete",
            name="programmation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="gsl_programmation.programmationprojet",
                verbose_name="Programmation projet",
            ),
        ),
        migrations.AlterField(
            model_name="lettrenotification",
            name="programmation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="gsl_programmation.programmationprojet",
                verbose_name="Programmation projet",
            ),
        ),
        migrations.CreateModel(
            name="LettreRefus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Contenu HTML du document, utilisé pour les exports.",
                        verbose_name="Contenu du document",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Taille du document"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modele",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_notification.modelelettrerefus",
                    ),
                ),
                (
                    "programmation_projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s",
                        to="gsl_programmation.programmationprojet",
                        verbose_name="Programmation projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettre de refus ou classement sans suite",
                "verbose_name_plural": "Lettres de refus ou classement sans suite",
            },
            bases=(gsl_notification.models.VerboseNameMixin, models.Model),
        ),
    ]
