# Generated by Django 6.0.5 on 2026-08-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0023_alter_arrete_programmation_projet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrete",
            name="with_qr_code",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lettrenotification",
            name="with_qr_code",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lettrerefus",
            name="with_qr_code",
            field=models.BooleanField(default=True),
        ),
    ]
