# Generated by Django 6.0.7 on 2026-08-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_notification",
            "0024_arrete_with_qr_code_lettrenotification_with_qr_code_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exportjob",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("arrete", "Arrêté"),
                    ("lettre", "Lettre de notification"),
                    ("arrete_et_lettre", "Arrêté et lettre"),
                    ("refus", "Lettre de refus ou de classement sans suite"),
                ],
                max_length=32,
            ),
        ),
    ]
