# Generated by Django 6.0.7 on 2026-08-18 11:53

import django.db.models.deletion
import gsl_notification.models
import gsl_notification.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_notification",
            "0024_arrete_with_qr_code_lettrenotification_with_qr_code_and_more",
        ),
        ("gsl_programmation", "0026_add_min_value_validator_to_enveloppe_montant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LettreRefusSignee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "last_scan",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dernière analyse antivirus"
                    ),
                ),
                (
                    "is_infected",
                    models.BooleanField(null=True, verbose_name="Fichier infecté"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="lettre_refus_signee/",
                        validators=[
                            gsl_notification.validators.document_file_validator
                        ],
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "programmation_projet",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lettre_refus_signee",
                        to="gsl_programmation.programmationprojet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lettre de notification signée",
                "verbose_name_plural": "Lettres de notification signées",
            },
            bases=(gsl_notification.models.VerboseNameMixin, models.Model),
        ),
    ]
