# Generated by Django 6.0.7 on 2026-08-19 09:04

import gsl_notification.models
import gsl_notification.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0025_lettrerefussignee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lettrerefussignee",
            options={
                "verbose_name": "Lettre de refus signée",
                "verbose_name_plural": "Lettres de refus signées",
            },
        ),
        migrations.AlterField(
            model_name="annexe",
            name="file",
            field=models.FileField(
                upload_to=gsl_notification.models.uploaded_document_upload_to,
                validators=[gsl_notification.validators.document_file_validator],
            ),
        ),
        migrations.AlterField(
            model_name="lettreetarretesignes",
            name="file",
            field=models.FileField(
                upload_to=gsl_notification.models.uploaded_document_upload_to,
                validators=[gsl_notification.validators.document_file_validator],
            ),
        ),
        migrations.AlterField(
            model_name="lettrerefussignee",
            name="file",
            field=models.FileField(
                upload_to=gsl_notification.models.uploaded_document_upload_to,
                validators=[gsl_notification.validators.document_file_validator],
            ),
        ),
    ]
