repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: "v0.9.9"
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/djlint/djLint
  rev: v1.36.4
  hooks:
    - id: djlint-reformat-django
    - id: djlint-django
- repo: https://github.com/thibaudcolas/pre-commit-stylelint
  rev: v16.23.1
  hooks:
    - id: stylelint
      args: [--fix]
- repo: https://github.com/standard/standard
  rev: master
  hooks:
    - id: standard