repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: "v0.5.1"
  hooks:
    - id: ruff-format
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
- repo: https://github.com/djlint/djLint
  rev: v1.36.3
  hooks:
    - id: djlint-reformat-django
    - id: djlint-django
