# Generated by Django 5.1.4 on 2025-02-05 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gsl_programmation", "0006_auto_20250205_1130"),
        ("gsl_projet", "0010_alter_demandeur_siret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    state_operations = [
        migrations.CreateModel(
            name="Simulation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(verbose_name="Titre")),
                (
                    "slug",
                    models.SlugField(
                        max_length=120, unique=True, verbose_name="Clé d’URL"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enveloppe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_programmation.enveloppe",
                        verbose_name="Dotation associée",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation de programmation",
                "verbose_name_plural": "Simulations de programmation",
            },
        ),
        migrations.CreateModel(
            name="SimulationProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant"
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "🔄 En traitement"),
                            ("valid", "✅  Accepté"),
                            ("provisoire", "✔️ Accepté provisoirement"),
                            ("cancelled", "❌ Refusé"),
                        ],
                        default="draft",
                        verbose_name="État",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enveloppe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_programmation.enveloppe",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_projet.projet",
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_simulation.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Simulation de programmation projet",
                "verbose_name_plural": "Simulations de programmation projet",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("projet", "simulation", "enveloppe"),
                        name="unique_projet_enveloppe_projet",
                        nulls_distinct=True,
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "valid")),
                        fields=("projet", "enveloppe"),
                        name="unique_valid_simulation_per_project",
                    ),
                ],
            },
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
