# Generated by Django 5.1.4 on 2025-02-19 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0008_alter_programmationprojet_status"),
        ("gsl_projet", "0012_alter_projet_status"),
        ("gsl_simulation", "0003_alter_simulationprojet_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="simulationprojet",
            name="unique_projet_enveloppe_projet",
        ),
        migrations.AddConstraint(
            model_name="simulationprojet",
            constraint=models.UniqueConstraint(
                fields=("projet", "simulation", "enveloppe"),
                name="unique_projet_enveloppe_simulation",
                nulls_distinct=True,
            ),
        ),
    ]
