# Generated by Django 5.1.4 on 2025-02-26 11:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_simulation",
            "0005_remove_simulationprojet_unique_projet_enveloppe_simulation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationprojet",
            name="enveloppe",
        ),
    ]
