# Generated by Django 5.1.4 on 2025-02-28 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0006_remove_simulationprojet_enveloppe"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="simulationprojet",
            options={
                "verbose_name": "Projet de simulation",
                "verbose_name_plural": "Projets de simulation",
            },
        ),
    ]
