# Generated by Django 5.1.4 on 2025-03-04 11:44

from django.db import migrations, models


def update_simulation_projet_status(apps, schema_editor):
    SimulationProjet = apps.get_model("gsl_simulation", "SimulationProjet")
    SimulationProjet.objects.filter(status="unanswered").update(status="dismissed")


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0008_alter_simulationprojet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationprojet",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "🔄 En traitement"),
                    ("valid", "✅ Accepté"),
                    ("provisoire", "✔️ Accepté provisoirement"),
                    ("cancelled", "❌ Refusé"),
                    ("dismissed", "⛔️ Classé sans suite"),
                ],
                default="draft",
                verbose_name="État",
            ),
        ),
        migrations.RunPython(update_simulation_projet_status),
    ]
