# Generated by Django 5.1.7 on 2025-04-16 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0013_initialize_dotation_projet_for_simulation_projets"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationprojet",
            name="projet",
        ),
    ]
