# Generated by Django 5.2.6 on 2025-11-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0023_alter_enveloppe_perimetre"),
        ("gsl_simulation", "0018_remove_simulationprojet_taux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="enveloppe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_programmation.enveloppe",
                verbose_name="Enveloppe de dotation associée",
            ),
        ),
    ]
