# Generated by Django 5.2.8 on 2026-03-05 16:21

import gsl_simulation.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0021_alter_simulation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="columns_visibility",
            field=models.JSONField(
                blank=True,
                default=None,
                null=True,
                validators=[gsl_simulation.models.validate_columns_visibility],
                verbose_name="Colonnes affichées",
            ),
        ),
    ]
