# Generated by Django 5.2.8 on 2026-03-10 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0022_simulation_columns_visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationprojet",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant",
            ),
        ),
    ]
