# Generated by Django 6.0.3 on 2026-04-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0024_simulation_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="downloaded_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                null=True,
                verbose_name="Date de téléchargement",
            ),
        ),
    ]
