# Generated by Django 6.0.3 on 2026-04-21 14:08

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0025_simulation_downloaded_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkStatusJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_status",
                    models.CharField(
                        choices=[
                            ("draft", "🔄 En traitement"),
                            ("valid", "✅ Accepté"),
                            ("provisionally_accepted", "✔️ Accepté provisoirement"),
                            ("provisionally_refused", "✖️ Refusé provisoirement"),
                        ],
                        max_length=32,
                        verbose_name="Statut cible",
                    ),
                ),
                ("simulation_projet_ids", models.JSONField(default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("done", "Terminé"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("processed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_simulation.simulation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Changement de statut en masse",
                "verbose_name_plural": "Changements de statut en masse",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="bulkstatusjob",
            constraint=models.UniqueConstraint(
                condition=Q(("status__in", ("pending", "running"))),
                fields=("simulation",),
                name="uq_bulkstatusjob_active_per_simulation",
            ),
        ),
    ]
