# Generated by Django 6.0.3 on 2026-05-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0026_bulkstatusjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkstatusjob",
            name="target_status",
            field=models.CharField(
                choices=[
                    ("draft", "🔄 En traitement"),
                    ("valid", "✅ Accepté"),
                    ("provisionally_accepted", "✔️ Accepté provisoirement"),
                    ("provisionally_refused", "✖️ Refusé provisoirement"),
                    ("cancelled", "❌ Refusé"),
                    ("dismissed", "⛔️ Classé sans suite"),
                ],
                max_length=32,
                verbose_name="Statut cible",
            ),
        ),
    ]
