# Generated by Django 5.1.1 on 2024-10-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegue",
            name="proconnect_chorusdt",
            field=models.CharField(
                default="", verbose_name="Entité ministérielle / Matricule Agent"
            ),
        ),
        migrations.AddField(
            model_name="collegue",
            name="proconnect_idp_id",
            field=models.UUIDField(null=True, verbose_name="Identifiant du FI"),
        ),
        migrations.AddField(
            model_name="collegue",
            name="proconnect_siret",
            field=models.CharField(default="", verbose_name="SIRET"),
        ),
        migrations.AddField(
            model_name="collegue",
            name="proconnect_sub",
            field=models.UUIDField(
                null=True, verbose_name="Identifiant unique proconnect"
            ),
        ),
        migrations.AddField(
            model_name="collegue",
            name="proconnect_uid",
            field=models.CharField(default="", verbose_name="ID chez le FI"),
        ),
    ]
