# Generated by Django 5.1.1 on 2024-11-08 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0003_commune_departement_region_adresse_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresse",
            name="commune",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.commune",
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="postal_code",
            field=models.CharField(blank=True, verbose_name="Code postal"),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="street_address",
            field=models.CharField(blank=True, verbose_name="Adresse"),
        ),
    ]
