# Generated by Django 5.1.4 on 2024-12-19 10:48

from django.db import migrations


def create_territoires_inconnus(apps, schema_editor):
    # We can't import the Region, Departement and Arrondissement models directly,
    # as it may newer versions than this migration expects.
    # We use the historical version.
    Region = apps.get_model("gsl_core", "Region")
    Departement = apps.get_model("gsl_core", "Departement")
    Arrondissement = apps.get_model("gsl_core", "Arrondissement")
    region_inconnue = Region.objects.create(insee_code="xxx", name="Inconnue")
    departement_inconnu = Departement.objects.create(
        insee_code="xxx", name="Inconnu", region=region_inconnue
    )
    Arrondissement.objects.create(
        insee_code="xxx", name="Inconnu", departement=departement_inconnu
    )


def delete_territoires_inconnus(apps, schema_editor):
    Arrondissement = apps.get_model("gsl_core", "Arrondissement")
    Arrondissement.objects.filter(insee_code="xxx").delete()
    Departement = apps.get_model("gsl_core", "Departement")
    Departement.objects.filter(insee_code="xxx").delete()
    Region = apps.get_model("gsl_core", "Region")
    Region.objects.filter(insee_code="xxx").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0005_alter_departement_options_alter_region_options_and_more"),
    ]

    operations = [
        migrations.RunPython(create_territoires_inconnus, delete_territoires_inconnus)
    ]
