# Generated by Django 5.1.4 on 2024-12-19 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0006_create_territoires_inconnus"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="arrondissement",
            field=models.ForeignKey(
                default="xxx",
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.arrondissement",
            ),
            preserve_default=False,
        ),
    ]
