# Generated by Django 5.2.4 on 2025-09-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegue",
            name="ds_id",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="ID chez Démarches Simplifiées"
            ),
        ),
    ]
