# Generated by Django 5.2.7 on 2025-10-21 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0009_collegue_ds_id"),
        (
            "gsl_demarches_simplifiees",
            "0017_critereeligibilitedetr_detr_category_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collegue",
            name="ds_id",
        ),
        migrations.AddField(
            model_name="collegue",
            name="ds_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gsl_demarches_simplifiees.profile",
            ),
        ),
    ]
