# Generated by Django 5.2.7 on 2025-10-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0010_remove_collegue_ds_id_collegue_ds_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegue",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email address"
            ),
        ),
    ]
