# Generated by Django 5.2.8 on 2026-01-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0011_alter_collegue_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="departement",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
