# Generated by Django 5.2.8 on 2026-02-10 09:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0013_alter_collegue_is_staff_alter_collegue_is_superuser"),
        ("gsl_core", "0013_collegue_comment"),
    ]

    operations = []
