# Generated by Django 5.2.8 on 2026-02-12 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0014_alter_adresse_created_at_alter_adresse_updated_at_and_more"),
        ("gsl_core", "0014_merge_20260210_1059"),
    ]

    operations = []
