# Generated by Django 6.0.5 on 2026-06-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0015_merge_20260212_1416"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departement",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Préfecture embarquée disposant d'utilisateurs (utilisé pour les statistiques). N'influence plus la synchronisation des dossiers.",
                verbose_name="Préfecture embarquée",
            ),
        ),
    ]
