# Generated by Django 6.0.7 on 2026-09-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0016_alter_departement_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="Import"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="État"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "État d'import",
                "verbose_name_plural": "États d'import",
            },
        ),
    ]
