# Generated by Django 6.0.7 on 2026-09-14 14:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0017_commune_siren"),
        ("gsl_core", "0017_importstate"),
    ]

    operations = []
