# Generated by Django 6.0.7 on 2026-09-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0017_importstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="commune",
            name="siren",
            field=models.CharField(
                blank=True,
                help_text="Identifiant SIREN de la commune (cf. la commande import_commune_siren).",
                max_length=9,
                verbose_name="SIREN",
            ),
        ),
    ]
