# Generated by Django 5.2.2 on 2025-06-18 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="arretesigne",
            old_name="uploaded_at",
            new_name="created_at",
        ),
    ]
