# Generated by Django 5.2.3 on 2025-07-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0004_merge_20250627_1012"),
    ]

    operations = [
        migrations.AlterField(
            model_name="arrete",
            name="content",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Contenu HTML de l'arrêté, utilisé pour les exports.",
                verbose_name="Contenu de l'arrêté",
            ),
        ),
    ]
