# Generated by Django 5.2.4 on 2025-07-18 07:34

import django.db.models.deletion
from django.db import migrations, models


def remove_all_arretes(apps, schema_editor):
    Arrete = apps.get_model("gsl_notification", "Arrete")
    Arrete.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0006_modelearrete"),
    ]

    operations = [
        migrations.RunPython(
            remove_all_arretes,
            migrations.RunPython.noop,
        ),  # We do it because we add a mandatory foreign key
        migrations.AddField(
            model_name="arrete",
            name="modele",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_notification.modelearrete",
            ),
        ),
    ]
