# Generated by Django 5.2.6 on 2025-10-17 15:02

import gsl.notification.models
import gsl.notification.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0012_arreteetlettresignes_delete_arretesigne"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annexe",
            name="file",
            field=models.FileField(
                upload_to="annexe/",
                validators=[gsl.notification.validators.document_file_validator],
            ),
        ),
        migrations.AlterField(
            model_name="arreteetlettresignes",
            name="file",
            field=models.FileField(
                upload_to="arrete_et_lettre_signes/",
                validators=[gsl.notification.validators.document_file_validator],
            ),
        ),
        migrations.AlterField(
            model_name="modelearrete",
            name="logo",
            field=models.FileField(
                help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                upload_to=gsl.notification.models.tokenized_file_in_timestamped_folder,
                validators=[gsl.notification.validators.logo_file_validator],
                verbose_name="Logo situé en haut à gauche",
            ),
        ),
        migrations.AlterField(
            model_name="modelelettrenotification",
            name="logo",
            field=models.FileField(
                help_text="Taille maximale : 20 Mo. Formats acceptés : jpg, png.",
                upload_to=gsl.notification.models.tokenized_file_in_timestamped_folder,
                validators=[gsl.notification.validators.logo_file_validator],
                verbose_name="Logo situé en haut à gauche",
            ),
        ),
    ]
