# Generated by Django 5.2.8 on 2026-01-15 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_notification",
            "0013_alter_annexe_file_alter_arreteetlettresignes_file_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="arrete",
            name="size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Taille du document"
            ),
        ),
        migrations.AddField(
            model_name="lettrenotification",
            name="size",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Taille du document"
            ),
        ),
    ]
