# Generated by Django 5.2.8 on 2026-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0015_add_antivirus_scan_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelearrete",
            name="is_infected",
            field=models.BooleanField(null=True, verbose_name="Fichier infecté"),
        ),
        migrations.AddField(
            model_name="modelearrete",
            name="last_scan",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière analyse antivirus"
            ),
        ),
        migrations.AddField(
            model_name="modelelettrenotification",
            name="is_infected",
            field=models.BooleanField(null=True, verbose_name="Fichier infecté"),
        ),
        migrations.AddField(
            model_name="modelelettrenotification",
            name="last_scan",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Dernière analyse antivirus"
            ),
        ),
    ]
