# Generated by Django 6.0.3 on 2026-04-29 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0017_migrate_mention_ids_to_keys"),
        ("gsl_programmation", "0026_add_min_value_validator_to_enveloppe_montant"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ArreteEtLettreSignes",
            new_name="LettreEtArreteSignes",
        ),
        migrations.AlterModelOptions(
            name="lettreetarretesignes",
            options={
                "verbose_name": "Lettre et arrêté signés",
                "verbose_name_plural": "Lettres et arrêtés signés",
            },
        ),
        migrations.AlterField(
            model_name="lettreetarretesignes",
            name="programmation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lettre_et_arrete_signes",
                to="gsl_programmation.programmationprojet",
            ),
        ),
    ]
