# Generated by Django 6.0.5 on 2026-05-29 09:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_notification",
            "0018_rename_arreteetlettresignes_to_lettreetarretesignes",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentImportJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("done", "Terminé"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("s3_keys", models.JSONField(default=list)),
                ("total_pages", models.PositiveIntegerField(default=0)),
                ("processed_pages", models.PositiveIntegerField(default=0)),
                ("result", models.JSONField(default=dict)),
                ("remove_qr_code", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Import de documents signés",
                "verbose_name_plural": "Imports de documents signés",
                "ordering": ("-created_at",),
            },
        ),
    ]
