# Generated by Django 6.0.5 on 2026-06-16 18:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0019_documentimportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pp_ids", models.JSONField(default=list)),
                ("attr_names", models.JSONField(default=list)),
                (
                    "export_format",
                    models.CharField(
                        choices=[
                            ("un_pdf_par_document", "Un PDF par document"),
                            ("un_seul_pdf_ensemble", "Un seul PDF pour l'ensemble"),
                            ("un_pdf_par_projet", "Un PDF par projet"),
                            (
                                "un_seul_pdf_groupe_par_projet",
                                "Un seul PDF groupé par projet",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("arrete", "Arrêté"),
                            ("lettre", "Lettre de notification"),
                            ("arrete_et_lettre", "Arrêté et lettre"),
                        ],
                        max_length=32,
                    ),
                ),
                ("with_qr_code", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("failed", "Échec"),
                            ("done", "Terminé"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("step", models.PositiveSmallIntegerField(default=1)),
                ("total_steps", models.PositiveSmallIntegerField(default=2)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("total", models.PositiveIntegerField(default=0)),
                ("download_url", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Export de documents",
                "verbose_name_plural": "Exports de documents",
                "ordering": ("-created_at",),
            },
        ),
    ]
