# Generated by Django 6.0.5 on 2026-07-29 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0021_modelelettrerefus"),
        ("gsl_programmation", "0026_add_min_value_validator_to_enveloppe_montant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lettrenotification",
            name="programmation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lettre",
                to="gsl_programmation.programmationprojet",
                verbose_name="Programmation projet",
            ),
        ),
    ]
