# Generated by Django 6.0.7 on 2026-08-26 07:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_notification", "0025_alter_exportjob_document_type"),
        (
            "gsl_notification",
            "0026_alter_lettrerefussignee_options_alter_annexe_file_and_more",
        ),
    ]

    operations = []
