# Generated by Django 5.1.4 on 2025-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_simulation",
            "0002_remove_simulationprojet_unique_valid_simulation_per_project",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationprojet",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "🔄 En traitement"),
                    ("valid", "✅ Accepté"),
                    ("provisoire", "✔️ Accepté provisoirement"),
                    ("cancelled", "❌ Refusé"),
                ],
                default="draft",
                verbose_name="État",
            ),
        ),
    ]
