# Generated by Django 5.1.7 on 2025-04-29 15:00

from django.db import migrations


def update_provisoire_simulation_projet_status(apps, schema_editor):
    SimulationProjet = apps.get_model("gsl_simulation", "SimulationProjet")
    SimulationProjet.objects.filter(status="provisoire").update(
        status="provisionally_accepted"
    )


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0015_alter_simulationprojet_status"),
    ]

    operations = [
        migrations.RunPython(
            update_provisoire_simulation_projet_status,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
