# Generated by Django 5.1.7 on 2025-04-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0016_auto_20250429_1700"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationprojet",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "🔄 En traitement"),
                    ("valid", "✅ Accepté"),
                    ("provisionally_accepted", "✔️ Accepté provisoirement"),
                    ("provisionally_refused", "✖️ Refusé provisoirement"),
                    ("cancelled", "❌ Refusé"),
                    ("dismissed", "⛔️ Classé sans suite"),
                ],
                default="draft",
                verbose_name="État",
            ),
        ),
    ]
