# Generated by Django 5.1.7 on 2025-05-14 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0017_alter_simulationprojet_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="simulationprojet",
            name="taux",
        ),
    ]
