# Generated by Django 5.2.6 on 2025-11-13 15:09

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0019_alter_simulation_enveloppe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=120,
                populate_from="title",
                unique=True,
                verbose_name="Clé d’URL",
            ),
        ),
    ]
