# Generated by Django 5.2.8 on 2026-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0020_alter_simulation_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="simulation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="simulationprojet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="simulationprojet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
    ]
