# Generated by Django 6.0.3 on 2026-04-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0023_alter_simulationprojet_montant"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulation",
            name="filters",
            field=models.JSONField(
                blank=True, default=None, null=True, verbose_name="Filtres appliqués"
            ),
        ),
    ]
