# Generated by Django 6.0.7 on 2026-09-22 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0041_enveloppe"),
        (
            "gsl_simulation",
            "0028_rename_dotation_projet_simulationprojet_enveloppe_projet",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="enveloppe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_projet.enveloppe",
                verbose_name="Enveloppe de dotation associée",
            ),
        ),
    ]
