# Generated by Django 6.0.7 on 2026-09-28 15:12

from django.db import migrations

BULK_STATUS_ACTION = "simulation_status"


def move_bulk_status_jobs(apps, schema_editor):
    BulkStatusJob = apps.get_model("gsl_simulation", "BulkStatusJob")
    BulkActionsJob = apps.get_model("gsl_core", "BulkActionsJob")

    for job in BulkStatusJob.objects.all():
        BulkActionsJob.objects.create(
            id=job.id,
            action=BULK_STATUS_ACTION,
            created_by_id=job.created_by_id,
            object_ids=job.simulation_projet_ids,
            params={
                "simulation_id": job.simulation_id,
                "target_status": job.target_status,
            },
            status=job.status,
            processed=job.processed,
            errors=[
                {
                    "object_id": error.get("simulation_projet_id"),
                    "label": error.get("label"),
                    "message": error.get("message"),
                }
                for error in job.errors
            ],
            lock_key=f"simulation:{job.simulation_id}",
        )
        # auto_now_add / auto_now overwrite the dates on create: restore them.
        BulkActionsJob.objects.filter(pk=job.id).update(
            created_at=job.created_at, updated_at=job.updated_at
        )


def remove_moved_bulk_status_jobs(apps, schema_editor):
    BulkActionsJob = apps.get_model("gsl_core", "BulkActionsJob")
    BulkActionsJob.objects.filter(action=BULK_STATUS_ACTION).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0021_rename_errors_bulkactionsjob_report_and_more"),
        (
            "gsl_simulation",
            "0028_rename_dotation_projet_simulationprojet_enveloppe_projet",
        ),
    ]

    operations = [
        migrations.RunPython(move_bulk_status_jobs, remove_moved_bulk_status_jobs),
    ]
