# Generated by Django 6.0.7 on 2026-09-28 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_simulation", "0029_move_bulkstatusjob_to_bulkactionsjob"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="bulkstatusjob",
            name="uq_bulkstatusjob_active_per_simulation",
        ),
        migrations.DeleteModel(
            name="BulkStatusJob",
        ),
    ]
