# Generated by Django 6.0.5 on 2026-08-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SuiviFinancier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "ej",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        verbose_name="EJ (n° pièce Chorus)",
                    ),
                ),
                (
                    "dn",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Numéro DN"
                    ),
                ),
                (
                    "dotation",
                    models.CharField(
                        blank=True,
                        choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                        max_length=4,
                        verbose_name="Dotation",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant"
                    ),
                ),
                (
                    "date_transaction",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Date de la transaction",
                    ),
                ),
                (
                    "date_engagement",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'engagement"
                    ),
                ),
                (
                    "tv",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("50", "Demandes d'achat"),
                            ("51", "Commandes d'achat"),
                            ("52", "Engagements frais de déplacement"),
                            ("54", "Factures"),
                            ("57", "Paiements"),
                            ("58", "Demandes d'acompte"),
                            ("60", "Pièces préenregistrées"),
                            ("6B", "Liste de vérification FI-CA"),
                            ("61", "Acomptes"),
                            ("64", "Réimputations de fonds"),
                            ("65", "Engagement de fonds"),
                            ("66", "Transferts"),
                            ("80", "Blocage de fonds"),
                            ("81", "Réservation de fonds"),
                            ("82", "Pré-engagement de fonds"),
                            ("83", "Prévision de recettes"),
                            ("84", "Réservation de paiements"),
                            ("95", "Écritures de coûts secondaires (CO)"),
                        ],
                        max_length=5,
                        verbose_name="Type de pièce",
                    ),
                ),
                (
                    "type_montant",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("0100", "Original"),
                            ("0150", "Modification"),
                            ("0200", "Réduction"),
                            ("0210", "Réduction compensation de chèque"),
                            ("0220", "Modification par réévaluation"),
                            ("0250", "Payé"),
                            ("0260", "Payé compensation de chèque"),
                            ("0300", "Report exercice précédent (engagements)"),
                            ("0350", "Report des engagements"),
                            (
                                "0351",
                                "Report des engagements : report de fonds engagés",
                            ),
                            (
                                "0352",
                                "Report des engagements : réduction de fonds engagés",
                            ),
                            ("0360", "Solde des exercices précédents"),
                            ("0400", "Entrée de blocage"),
                            ("0500", "Ajustement par pièce suivante"),
                            ("0600", "Changement d'imputation émetteur"),
                            ("0650", "Changement d'imputation récepteur"),
                            ("0700", "Décompte sortie"),
                            ("0750", "Décompte entrée"),
                        ],
                        max_length=10,
                        verbose_name="Type de montant",
                    ),
                ),
                (
                    "poste",
                    models.CharField(blank=True, max_length=10, verbose_name="Poste"),
                ),
                (
                    "compte_general",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Compte général"
                    ),
                ),
            ],
            options={
                "verbose_name": "Suivi financier",
                "verbose_name_plural": "Suivis financiers",
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "ej",
                            "dn",
                            "dotation",
                            "montant",
                            "date_transaction",
                            "date_engagement",
                            "tv",
                            "type_montant",
                            "poste",
                            "compte_general",
                        ),
                        name="uniq_suivi_financier_ligne",
                        nulls_distinct=False,
                    )
                ],
            },
        ),
    ]
