from typing import Literal

DOTATION_DETR = "DETR"
DOTATION_DSIL = "DSIL"
DOTATIONS = (DOTATION_DETR, DOTATION_DSIL)
DOTATION_CHOICES = ((DOTATION_DETR, DOTATION_DETR), (DOTATION_DSIL, DOTATION_DSIL))

# TYPE
POSSIBLE_DOTATIONS = Literal["DETR", "DSIL"]

PROJET_STATUS_ACCEPTED = "accepted"
PROJET_STATUS_REFUSED = "refused"
PROJET_STATUS_PROCESSING = "processing"
PROJET_STATUS_DISMISSED = "dismissed"
PROJET_STATUS_CHOICES = (
    (PROJET_STATUS_ACCEPTED, "✅ Accepté"),
    (PROJET_STATUS_REFUSED, "❌ Refusé"),
    (PROJET_STATUS_PROCESSING, "🔄 En traitement"),
    (PROJET_STATUS_DISMISSED, "⛔️ Classé sans suite"),
)
PROJET_FINAL_STATUSES = [
    PROJET_STATUS_ACCEPTED,
    PROJET_STATUS_REFUSED,
    PROJET_STATUS_DISMISSED,
]

NOTIFICATION_STATUS_TO_GENERATE = "to_generate"
NOTIFICATION_STATUS_TO_SIGN = "to_sign"
NOTIFICATION_STATUS_TO_NOTIFY = "to_notify"
NOTIFICATION_STATUS_NOTIFIED = "notified"
NOTIFICATION_STATUS_CHOICES = (
    (NOTIFICATION_STATUS_TO_GENERATE, "À générer"),
    (NOTIFICATION_STATUS_TO_SIGN, "À signer"),
    (NOTIFICATION_STATUS_TO_NOTIFY, "À notifier"),
    (NOTIFICATION_STATUS_NOTIFIED, "Notifié"),
)

ARRETE = "arrete"
LETTRE = "lettre"
LETTRE_REFUS = "refus"

LETTRE_ET_ARRETE_SIGNES = "lettre_et_arrete_signes"
ANNEXE = "annexe"

MIN_DEMANDE_MONTANT_FOR_AVIS_DETR = 100_000

ANNUAIRE_ENTREPRISE_URL = "https://annuaire-entreprises.data.gouv.fr/entreprise/"
