# Generated by Django 5.1.4 on 2024-12-20 16:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0001_initial"),
        ("gsl_projet", "0008_alter_demandeur_arrondissement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Scenario",
            new_name="Simulation",
        ),
        migrations.RemoveConstraint(
            model_name="simulationprojet",
            name="unique_projet_enveloppe_projet",
        ),
        migrations.RenameField(
            model_name="simulationprojet",
            old_name="scenario",
            new_name="simulation",
        ),
        migrations.AddConstraint(
            model_name="simulationprojet",
            constraint=models.UniqueConstraint(
                fields=("projet", "simulation", "enveloppe"),
                name="unique_projet_enveloppe_projet",
                nulls_distinct=True,
            ),
        ),
    ]
