# Generated by Django 5.1.7 on 2025-04-02 12:46

from django.db import migrations, models


def set_dotation(apps, schema_editor):
    Enveloppe = apps.get_model("gsl_programmation", "Enveloppe")
    Enveloppe.objects.filter(type="DETR").update(dotation="DETR")
    Enveloppe.objects.filter(type="DSIL").update(dotation="DSIL")


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_programmation", "0008_alter_programmationprojet_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enveloppe",
            name="unicity_by_perimeter_and_type",
        ),
        migrations.AddField(
            model_name="enveloppe",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                null=True,
                verbose_name="Dotation",
            ),
        ),
        migrations.AddConstraint(
            model_name="enveloppe",
            constraint=models.UniqueConstraint(
                fields=("annee", "dotation", "perimetre"),
                name="unicity_by_perimeter_and_dotation",
            ),
        ),
        migrations.RunPython(set_dotation),
    ]
