# Generated by Django 5.1.7 on 2025-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_programmation",
            "0009_remove_enveloppe_unicity_by_perimeter_and_type_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enveloppe",
            name="type",
        ),
        migrations.AlterField(
            model_name="enveloppe",
            name="dotation",
            field=models.CharField(
                choices=[("DETR", "DETR"), ("DSIL", "DSIL")], verbose_name="Dotation"
            ),
        ),
    ]
