# Generated by Django 5.1.7 on 2025-04-14 14:56

import django.db.models.deletion
from django.db import migrations, models


def set_dotation_projet_for_programmation_projets(apps, schema_editor):
    ProgrammationProjet = apps.get_model("gsl_programmation", "ProgrammationProjet")
    DotationProjet = apps.get_model("gsl_projet", "DotationProjet")
    for programmation_projet in ProgrammationProjet.objects.all():
        try:
            programmation_projet.dotation_projet = DotationProjet.objects.get(
                projet=programmation_projet.projet,
                dotation=programmation_projet.enveloppe.dotation,
            )
            programmation_projet.save()
        except AttributeError as e:
            print(
                f"Could not find enveloppe dotation for programmation projet {programmation_projet.pk}",
                e,
            )
        except DotationProjet.DoesNotExist as e:
            print(
                f"Could not find dotation projet for programmation projet {programmation_projet.pk}",
                e,
            )


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0010_remove_enveloppe_type_alter_enveloppe_dotation"),
        ("gsl_projet", "0018_dotationprojet"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmationprojet",
            name="dotation_projet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_projet.dotationprojet",
                verbose_name="Dotation projet",
            ),
        ),
        migrations.RunPython(
            set_dotation_projet_for_programmation_projets,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
