# Generated by Django 5.1.7 on 2025-04-14 15:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0012_alter_programmationprojet_dotation_projet"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="programmationprojet",
            name="unique_projet_enveloppe",
        ),
    ]
