# Generated by Django 5.1.7 on 2025-04-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_programmation",
            "0013_remove_programmationprojet_unique_projet_enveloppe",
        ),
        ("gsl_projet", "0018_dotationprojet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmationprojet",
            name="projet",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_projet.projet",
                verbose_name="Projet",
            ),
        ),
    ]
