# Generated by Django 5.1.7 on 2025-04-17 15:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0015_alter_programmationprojet_dotation_projet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmationprojet",
            name="projet",
        ),
    ]
