# Generated by Django 5.1.7 on 2025-05-14 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0016_remove_programmationprojet_projet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmationprojet",
            name="taux",
        ),
    ]
