# Generated by Django 5.2.5 on 2025-09-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0009_collegue_ds_id"),
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name="enveloppe",
            name="unicity_by_perimeter_and_dotation",
            constraint=models.UniqueConstraint(
                fields=("annee", "dotation", "perimetre"),
                name="unicity_by_perimeter_and_dotation",
                violation_error_message="Cette enveloppe est déjà programmée pour ce territoire et cette dotation.",
            ),
        ),
    ]
