# Generated by Django 5.2.7 on 2025-10-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0020_auto_20251016_1210"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enveloppe",
            name="deleguee_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_programmation.enveloppe",
                verbose_name="Enveloppe déléguée",
            ),
        ),
    ]
