# Generated by Django 5.2.7 on 2025-10-23 14:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0021_alter_enveloppe_deleguee_by"),
        ("gsl_programmation", "0021_merge_20251022_1611"),
    ]

    operations = []
