# Generated by Django 5.2.6 on 2025-11-12 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0011_alter_collegue_email"),
        ("gsl_programmation", "0022_merge_20251023_1625"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enveloppe",
            name="perimetre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.perimetre",
                verbose_name="Périmètre",
            ),
        ),
    ]
