# Generated by Django 5.2.6 on 2025-11-21 15:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0023_alter_enveloppe_perimetre"),
        ("gsl_projet", "0025_projet_notified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmationprojet",
            name="notified_at",
        ),
    ]
