# Generated by Django 6.0.7 on 2026-09-10 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gsl_core", "0017_importstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="FondsVertImportState",
            fields=[],
            options={
                "verbose_name": "État de l'import Fonds Vert",
                "verbose_name_plural": "État de l'import Fonds Vert",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("gsl_core.importstate",),
        ),
        migrations.CreateModel(
            name="Subvention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unique_key",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        unique=True,
                        verbose_name="Clé unique",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("dgcl", "DGCL"), ("fonds_vert", "Fonds Vert")],
                        max_length=20,
                        verbose_name="Source",
                    ),
                ),
                (
                    "siren",
                    models.CharField(db_index=True, max_length=9, verbose_name="SIREN"),
                ),
                ("exercice", models.PositiveSmallIntegerField(verbose_name="Exercice")),
                (
                    "dispositif",
                    models.CharField(max_length=80, verbose_name="Dispositif"),
                ),
                (
                    "programme",
                    models.PositiveSmallIntegerField(verbose_name="Programme"),
                ),
                ("intitule", models.TextField(verbose_name="Intitulé du projet")),
                (
                    "cout_total",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Coût total"
                    ),
                ),
                (
                    "montant_attribue",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant attribué",
                    ),
                ),
                (
                    "montant_demande",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant demandé",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("accepte", "Accepté"),
                            ("en_construction", "En construction"),
                            ("en_instruction", "En instruction"),
                            ("refuse", "Refusé"),
                            ("sans_suite", "Classé sans suite"),
                        ],
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "date_depot",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de dépôt"
                    ),
                ),
                (
                    "dossier_number",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Numéro de dossier DS"
                    ),
                ),
                (
                    "commune",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.commune",
                        verbose_name="Commune",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subvention",
                "verbose_name_plural": "Subventions",
                "ordering": ["-exercice"],
            },
        ),
    ]
