# Generated by Django 6.0.7 on 2026-09-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0018_merge_0017_commune_siren_0017_importstate"),
        ("gsl_stats", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="subvention",
            index=models.Index(
                fields=["source", "importer_key"], name="gsl_stats_s_source_cbd297_idx"
            ),
        ),
    ]
