# Generated by Django 6.0.7 on 2026-09-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_stats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subvention",
            name="source",
            field=models.CharField(
                choices=[
                    ("dgcl", "DGCL"),
                    ("fonds_vert", "Fonds Vert"),
                    ("fnadt", "FNADT"),
                ],
                max_length=20,
                verbose_name="Source",
            ),
        ),
    ]
