# Generated by Django 6.0.7 on 2026-08-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_stats", "0002_subventionfondsvert"),
    ]

    operations = [
        migrations.CreateModel(
            name="FondsVertImportState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_page",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Dernière page importée"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Mis à jour le"),
                ),
            ],
            options={
                "verbose_name": "État de l'import Fonds Vert",
                "verbose_name_plural": "État de l'import Fonds Vert",
            },
        ),
    ]
