# Generated by Django 6.0.7 on 2026-09-07 14:40

from django.db import migrations, models


def copy_beneficiaire_siren(apps, schema_editor):
    SubventionDgcl = apps.get_model("gsl_stats", "SubventionDgcl")
    SubventionFondsVert = apps.get_model("gsl_stats", "SubventionFondsVert")

    for model in (SubventionDgcl, SubventionFondsVert):
        subventions = list(model.objects.select_related("beneficiaire").iterator())
        for subvention in subventions:
            subvention.siren = subvention.beneficiaire.siren
        model.objects.bulk_update(subventions, ["siren"], batch_size=1000)


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_stats", "0003_fondsvertimportstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="subventiondgcl",
            name="siren",
            field=models.CharField(
                db_index=True, default="", max_length=9, verbose_name="SIREN"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subventionfondsvert",
            name="siren",
            field=models.CharField(
                db_index=True, default="", max_length=9, verbose_name="SIREN"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(copy_beneficiaire_siren, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name="subventiondgcl",
            unique_together={("exercice", "dispositif", "siren", "intitule")},
        ),
        migrations.RemoveField(
            model_name="subventiondgcl",
            name="beneficiaire",
        ),
        migrations.RemoveField(
            model_name="subventionfondsvert",
            name="beneficiaire",
        ),
        migrations.DeleteModel(
            name="Beneficiaire",
        ),
    ]
