# Generated by Django 5.1.4 on 2025-01-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0002_rename_scenario_simulation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulationprojet",
            name="taux",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Taux"
            ),
        ),
    ]
