# Generated by Django 5.1.4 on 2025-01-10 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0003_alter_simulationprojet_taux"),
        (
            "gsl_programmation",
            "0003_remove_enveloppe_unicity_by_perimeter_and_type_and_more",
        ),
    ]

    operations = []
