# Generated by Django 5.1.4 on 2025-01-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0004_merge_20250110_1226"),
    ]

    operations = [
        migrations.AlterField(
            model_name="simulation",
            name="slug",
            field=models.SlugField(
                max_length=120, unique=True, verbose_name="Clé d’URL"
            ),
        ),
    ]
