# Generated by Django 5.1.4 on 2025-02-05 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gsl_programmation", "0005_alter_simulation_slug"),
        ("gsl_projet", "0010_alter_demandeur_siret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    database_operations = [
        migrations.AlterModelTable("Simulation", "gsl_simulation_simulation"),
        migrations.AlterModelTable(
            "SimulationProjet", "gsl_simulation_simulationprojet"
        ),
    ]

    state_operations = [
        migrations.DeleteModel("Simulation"),
        migrations.DeleteModel("SimulationProjet"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations, state_operations=state_operations
        )
    ]
