# Generated by Django 5.1.4 on 2025-02-05 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0006_auto_20250205_1130"),
        ("gsl_projet", "0010_alter_demandeur_siret"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammationProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("accepted", "✅  Accepté"), ("refused", "❌ Refusé")],
                        default="accepted",
                        verbose_name="État",
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant"
                    ),
                ),
                (
                    "taux",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="Taux"
                    ),
                ),
                (
                    "justification",
                    models.TextField(
                        blank=True, default="", verbose_name="Justification"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de notification"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de dernière modification"
                    ),
                ),
                (
                    "enveloppe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_programmation.enveloppe",
                        verbose_name="Enveloppe",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_projet.projet",
                        verbose_name="Projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programmation projet",
                "verbose_name_plural": "Programmations projet",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("enveloppe", "projet"),
                        name="unique_projet_enveloppe",
                        nulls_distinct=True,
                    )
                ],
            },
        ),
    ]
