# Generated by Django 5.1.4 on 2025-02-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0007_programmationprojet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmationprojet",
            name="status",
            field=models.CharField(
                choices=[("accepted", "✅ Accepté"), ("refused", "❌ Refusé")],
                default="accepted",
                verbose_name="État",
            ),
        ),
    ]
