# Generated by Django 5.1.7 on 2025-03-28 11:01

import django.db.models.deletion
from django.db import migrations, models


def initialize_dotation(apps, schema_editor):
    Enveloppe = apps.get_model("gsl_programmation", "Enveloppe")
    Dotation = apps.get_model("gsl_projet", "Dotation")

    for enveloppe in Enveloppe.objects.all():
        dotation_detr = Dotation.objects.get(label="DETR")
        dotation_dsil = Dotation.objects.get(label="DSIL")

        if enveloppe.type == "DETR":
            enveloppe.dotation = dotation_detr
        elif enveloppe.type == "DSIL":
            enveloppe.dotation = dotation_dsil
        else:
            enveloppe.dotation = None
        enveloppe.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0008_alter_programmationprojet_status"),
        ("gsl_projet", "0018_dotation"),
    ]

    operations = [
        migrations.AddField(
            model_name="enveloppe",
            name="dotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_projet.dotation",
                verbose_name="Dotation",
                null=True,  # Permet de gérer les valeurs nulles temporairement
            ),
        ),
        migrations.RunPython(initialize_dotation),
        migrations.AlterField(
            model_name="enveloppe",
            name="dotation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_projet.dotation",
                verbose_name="Dotation",
                null=False,
            ),
        ),
    ]
