# Generated by Django 5.1.7 on 2025-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_programmation", "0009_enveloppe_dotation"),
        ("gsl_projet", "0018_dotation"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enveloppe",
            name="unicity_by_perimeter_and_type",
        ),
        migrations.AddConstraint(
            model_name="enveloppe",
            constraint=models.UniqueConstraint(
                fields=("annee", "dotation", "perimetre"),
                name="unicity_by_perimeter_and_dotation",
            ),
        ),
    ]
