# Generated by Django 5.1.7 on 2025-04-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0014_alter_programmationprojet_projet"),
        ("gsl_projet", "0018_dotationprojet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmationprojet",
            name="dotation_projet",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programmation_projet",
                to="gsl_projet.dotationprojet",
                verbose_name="Dotation projet",
            ),
        ),
    ]
