# Generated by Django 5.2.1 on 2025-06-05 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arrete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(max_length=255, verbose_name="Numéro de l'arrêté"),
                ),
                ("date", models.DateField(verbose_name="Date de l'arrêté")),
                (
                    "document",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="arretes/",
                        verbose_name="Document de l'arrêté",
                    ),
                ),
                (
                    "content",
                    models.JSONField(
                        blank=True,
                        help_text="Contenu JSON de l'arrêté, utilisé pour les exports.",
                        null=True,
                        verbose_name="Contenu de l'arrêté",
                    ),
                ),
                (
                    "programmation_projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arretes",
                        to="gsl_programmation.programmationprojet",
                        verbose_name="Programmation projet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arrêté",
                "verbose_name_plural": "Arrêtés",
            },
        ),
    ]
