# Generated by Django 5.2.6 on 2025-10-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0017_remove_programmationprojet_taux"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmationprojet",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "✅ Accepté"),
                    ("refused", "❌ Refusé"),
                    ("dismissed", "⛔️ Classé sans suite"),
                ],
                default="accepted",
                verbose_name="État",
            ),
        ),
    ]
