# Generated by Django 5.2.6 on 2025-10-16 10:10

from django.db import migrations
from django.db.migrations import RunPython


def update_programmation_projets(apps, schema_editor):
    ProgrammationProjet = apps.get_model("gsl_programmation", "ProgrammationProjet")
    for programmation_projet in ProgrammationProjet.objects.all():
        delegation_root = programmation_projet.enveloppe
        while delegation_root.deleguee_by is not None:
            delegation_root = delegation_root.deleguee_by
        programmation_projet.enveloppe = delegation_root
        programmation_projet.save(update_fields=["enveloppe"])


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0019_auto_20251014_1528"),
    ]

    operations = [RunPython(update_programmation_projets)]
