# Generated by Django 5.2.6 on 2025-10-22 14:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0018_alter_programmationprojet_status"),
        ("gsl_programmation", "0020_auto_20251016_1210"),
    ]

    operations = []
