# Generated by Django 6.0.3 on 2026-03-31 11:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0025_enveloppe_created_at_enveloppe_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enveloppe",
            name="montant",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=14,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Montant",
            ),
        ),
    ]
