# Generated by Django 6.0.7 on 2026-09-15 07:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0026_add_min_value_validator_to_enveloppe_montant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmationprojet",
            name="justification",
        ),
    ]
