# Generated by Django 6.0.7 on 2026-09-16 11:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0027_remove_programmationprojet_justification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmationprojet",
            name="status",
        ),
    ]
