# Generated by Django 6.0.7 on 2026-09-24 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0029_delete_programmationprojet"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enveloppe",
            old_name="deleguee_by",
            new_name="parent",
        ),
        migrations.AlterField(
            model_name="enveloppe",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_programmation.enveloppe",
                verbose_name="Enveloppe parente",
            ),
        ),
    ]
