# Generated by Django 6.0.8 on 2026-10-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_ds_proxy", "0002_groupe_instructeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proxytoken",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Actif"),
        ),
    ]
