# Generated by Django 5.1.1 on 2024-11-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0004_alter_demandeur_address_alter_projet_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="assiette",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Assiette subventionnable",
            ),
        ),
    ]
