# Generated by Django 5.1.4 on 2024-12-18 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0006_projet_avis_commission_detr_projet_free_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="demandeur",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_projet.demandeur",
            ),
        ),
    ]
