# Generated by Django 5.1.4 on 2024-12-19 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0005_alter_departement_options_alter_region_options_and_more"),
        ("gsl_projet", "0007_projet_demandeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeur",
            name="arrondissement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.arrondissement",
            ),
        ),
    ]
