# Generated by Django 5.1.4 on 2025-01-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0009_remove_duplicated_demandeurs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeur",
            name="siret",
            field=models.CharField(unique=True, verbose_name="Siret"),
        ),
    ]
