# Generated by Django 5.1.4 on 2025-02-24 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0011_projet_perimetre"),
        ("gsl_projet", "0012_alter_projet_status"),
    ]

    operations = []
