# Generated by Django 5.1.4 on 2025-02-25 10:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0012_remove_demandeur_arrondissement_and_more"),
        ("gsl_projet", "0013_merge_0011_projet_perimetre_0012_alter_projet_status"),
    ]

    operations = []
