# Generated by Django 5.1.7 on 2025-03-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0015_alter_projet_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="is_attached_to_a_crte",
            field=models.BooleanField(
                default=False, verbose_name="Projet rattaché à un CRTE"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="is_in_qpv",
            field=models.BooleanField(
                default=False, verbose_name="Projet situé en QPV"
            ),
        ),
    ]
