# Generated by Django 5.1.7 on 2025-03-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0016_projet_is_attached_to_a_crte_projet_is_in_qpv"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="is_budget_vert",
            field=models.BooleanField(
                default=False,
                null=True,
                verbose_name="Projet concourant à la transition écologique au sens budget vert",
            ),
        ),
    ]
