# Generated by Django 5.1.7 on 2025-04-17 08:07

from django.db import migrations
from gsl.projet.constants import ProjetStatus


def initialize_projet_status(apps, schema_editor):
    Projet = apps.get_model("gsl_projet", "Projet")
    DotationProjet = apps.get_model("gsl_projet", "DotationProjet")
    for projet in Projet.objects.all():
        status = None
        projet_dotation_projets = DotationProjet.objects.filter(projet=projet)

        if not projet_dotation_projets:
            continue
        elif any(dp.status == ProjetStatus.ACCEPTED for dp in projet_dotation_projets):
            status = ProjetStatus.ACCEPTED
        elif any(
            dp.status == ProjetStatus.PROCESSING for dp in projet_dotation_projets
        ):
            status = ProjetStatus.PROCESSING
        elif any(dp.status == ProjetStatus.REFUSED for dp in projet_dotation_projets):
            status = ProjetStatus.REFUSED
        else:
            status = ProjetStatus.DISMISSED

        projet.status = status
        projet.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0019_alter_projet_status"),
    ]

    operations = [
        migrations.RunPython(
            initialize_projet_status, reverse_code=migrations.RunPython.noop
        ),
    ]
