# Generated by Django 5.1.7 on 2025-04-18 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0020_initialize_projet_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="assiette",
        ),
        migrations.RemoveField(
            model_name="projet",
            name="avis_commission_detr",
        ),
    ]
