# Generated by Django 5.2.1 on 2025-06-04 13:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0022_alter_dotationprojet_options_categoriedetr_and_more"),
        ("gsl_projet", "0022_projetnote"),
    ]

    operations = []
