# Generated by Django 5.2.2 on 2025-06-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0023_merge_20250604_1502"),
    ]

    operations = [
        migrations.AddField(
            model_name="categoriedetr",
            name="is_current",
            field=models.BooleanField(
                default=False,
                help_text="Indique si cette catégorie est utilisable sur la campagne actuelle ou non",
                verbose_name="Actuelle",
            ),
        ),
    ]
