# Generated by Django 5.2.8 on 2025-12-01 13:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0025_projet_notified_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="status",
        ),
    ]
