# Generated by Django 6.0.7 on 2026-09-15 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0037_backfill_dotation_projet_assiette"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dotationprojet",
            name="detr_categories",
        ),
        migrations.RemoveConstraint(
            model_name="categoriedetr",
            name="unique_by_departement_rang_annee",
        ),
        migrations.DeleteModel(
            name="CategorieDetr",
        ),
    ]
