# Generated by Django 6.0.7 on 2026-09-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0030_rename_deleguee_by_enveloppe_parent"),
        ("gsl_projet", "0040_rename_dotationprojet_enveloppeprojet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="enveloppeprojet",
            options={
                "default_manager_name": "objects",
                "verbose_name": "Enveloppe projet",
                "verbose_name_plural": "Enveloppes projet",
            },
        ),
        migrations.AlterUniqueTogether(
            name="enveloppeprojet",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="enveloppeprojet",
            name="is_courant",
            field=models.BooleanField(default=True, verbose_name="Courant"),
        ),
        migrations.AddConstraint(
            model_name="enveloppeprojet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_courant", True)),
                fields=("projet", "dotation"),
                name="un_seul_enveloppe_projet_courant_par_dotation",
                violation_error_message="Ce projet a déjà un enveloppe projet courant pour cette dotation.",
            ),
        ),
    ]
