# Generated by Django 6.0.7 on 2026-09-25 07:46

from collections import defaultdict

import django.db.models.deletion
from django.db import migrations, models

DOTATION_DETR = "DETR"
PREMIER_MOIS_DE_LA_CAMPAGNE_SUIVANTE = 10


def annee_de_campagne(date_depot):
    if date_depot.month >= PREMIER_MOIS_DE_LA_CAMPAGNE_SUIVANTE:
        return date_depot.year + 1
    return date_depot.year


def territoire_id(dotation, perimetre):
    """A DETR root enveloppe sits on a departement, a DSIL one on a region."""
    if dotation == DOTATION_DETR:
        return perimetre.departement_id
    return perimetre.region_id


def root_enveloppes(Enveloppe):
    racines = {}
    for enveloppe in Enveloppe.objects.filter(parent__isnull=True).select_related(
        "perimetre"
    ):
        cle = (
            enveloppe.dotation,
            enveloppe.annee,
            territoire_id(enveloppe.dotation, enveloppe.perimetre),
        )
        racines[cle] = enveloppe
    return racines


def create_root_enveloppe(Enveloppe, Perimetre, cle, racines):
    dotation, annee, territoire = cle
    if dotation == DOTATION_DETR:
        perimetre = Perimetre.objects.get(
            departement_id=territoire, arrondissement__isnull=True
        )
    else:
        perimetre = Perimetre.objects.get(
            region_id=territoire,
            departement__isnull=True,
            arrondissement__isnull=True,
        )
    precedente = racines.get((dotation, annee - 1, territoire))
    return Enveloppe.objects.create(
        dotation=dotation,
        annee=annee,
        perimetre=perimetre,
        montant=precedente.montant if precedente else 0,
    )


def backfill_enveloppe(apps, schema_editor):
    EnveloppeProjet = apps.get_model("gsl_projet", "EnveloppeProjet")
    Enveloppe = apps.get_model("gsl_programmation", "Enveloppe")
    Perimetre = apps.get_model("gsl_core", "Perimetre")

    racines = root_enveloppes(Enveloppe)

    groupes = defaultdict(list)
    a_remplir = EnveloppeProjet.objects.filter(enveloppe__isnull=True).select_related(
        "projet__dossier_ds__perimetre"
    )
    for enveloppe_projet in a_remplir.iterator():
        dossier = enveloppe_projet.projet.dossier_ds
        cle = (
            enveloppe_projet.dotation,
            annee_de_campagne(dossier.ds_date_depot),
            territoire_id(enveloppe_projet.dotation, dossier.perimetre),
        )
        groupes[cle].append(enveloppe_projet.id)

    for cle, ids in groupes.items():
        enveloppe = racines.get(cle)
        if enveloppe is None:
            enveloppe = create_root_enveloppe(Enveloppe, Perimetre, cle, racines)
        EnveloppeProjet.objects.filter(id__in=ids).update(enveloppe=enveloppe)


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_programmation", "0030_rename_deleguee_by_enveloppe_parent"),
        ("gsl_projet", "0041_alter_enveloppeprojet_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="enveloppeprojet",
            name="enveloppe_ssi_dotation_traitee",
        ),
        migrations.RemoveConstraint(
            model_name="enveloppeprojet",
            name="un_seul_enveloppe_projet_courant_par_dotation",
        ),
        migrations.RunPython(backfill_enveloppe, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="enveloppeprojet",
            name="enveloppe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_programmation.enveloppe",
                verbose_name="Enveloppe",
            ),
        ),
        migrations.AddConstraint(
            model_name="enveloppeprojet",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("date_programmation__isnull", True),
                        ("montant__isnull", True),
                        ("status", "processing"),
                    ),
                    models.Q(
                        models.Q(("status", "processing"), _negated=True),
                        ("date_programmation__isnull", False),
                        ("montant__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="montant_et_date_ssi_dotation_traitee",
                violation_error_message="Une dotation en traitement ne peut porter ni montant ni date de programmation, et une dotation traitée doit porter les deux.",
            ),
        ),
        migrations.AddConstraint(
            model_name="enveloppeprojet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_courant", True)),
                fields=("projet", "enveloppe"),
                name="un_seul_enveloppe_projet_courant_par_enveloppe",
                violation_error_message="Ce projet a déjà un enveloppe projet courant sur cette enveloppe.",
            ),
        ),
    ]
