# Generated by Django 6.0.7 on 2026-09-29 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0042_enveloppe_non_nulle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enveloppeprojet",
            name="dotation",
        ),
    ]
