# Generated by Django 6.0.3 on 2026-04-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gsl_demarches_simplifiees", "0054_add_porteur_de_projet_civilite_to_dossier"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProxyToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "key_hash",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="Empreinte de clé API",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Libellé")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "instructeurs",
                    models.ManyToManyField(
                        blank=True,
                        to="gsl_demarches_simplifiees.profile",
                        verbose_name="Instructeurs autorisés",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token proxy DS",
                "verbose_name_plural": "Tokens proxy DS",
            },
        ),
    ]
