# Generated by Django 5.1.1 on 2024-11-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gsl_core", "0003_commune_departement_region_adresse_and_more"),
        ("gsl_demarches_simplifiees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demandeur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("siret", models.CharField(verbose_name="Siret")),
                ("name", models.CharField(verbose_name="Nom")),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_core.adresse",
                    ),
                ),
                (
                    "arrondissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.arrondissement",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.departement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_core.adresse",
                    ),
                ),
                (
                    "arrondissement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.arrondissement",
                    ),
                ),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_projet.demandeur",
                    ),
                ),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.departement",
                    ),
                ),
                (
                    "dossier_ds",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_demarches_simplifiees.dossier",
                    ),
                ),
            ],
        ),
    ]
