# Generated by Django 5.1.1 on 2024-11-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0004_alter_adresse_commune_alter_adresse_postal_code_and_more"),
        ("gsl_projet", "0002_remove_projet_arrondissement_remove_projet_demandeur"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="gsl_core.adresse",
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="departement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.departement",
            ),
        ),
    ]
