# Generated by Django 5.1.1 on 2024-11-28 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0004_alter_adresse_commune_alter_adresse_postal_code_and_more"),
        ("gsl_projet", "0003_alter_projet_address_alter_projet_departement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demandeur",
            name="address",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gsl_core.adresse"
            ),
        ),
        migrations.AlterField(
            model_name="projet",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.adresse",
            ),
        ),
    ]
