# Generated by Django 5.1.4 on 2025-01-26 08:00

from django.db import migrations
from django.db.models import Count


def remove_duplicated_demandeurs(apps, schema_editor):
    Demandeur = apps.get_model("gsl_projet", "Demandeur")
    Projet = apps.get_model("gsl_projet", "Projet")

    for siret_dict in (
        Demandeur.objects.values("siret")
        .annotate(Count("siret"))
        .filter(siret__count__gt=1)
    ):
        siret = siret_dict["siret"]
        first_demandeur = Demandeur.objects.filter(siret=siret).first()
        for projet in Projet.objects.filter(demandeur__siret=siret):
            projet.demandeur = first_demandeur
            projet.save()
        for other_demandeur in Demandeur.objects.filter(siret=siret).exclude(
            id=first_demandeur.id
        ):
            other_demandeur.delete()


def nothing(apps, schema_editor):
    pass


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Person = apps.get_model("yourappname", "Person")
    for person in Person.objects.all():
        person.name = f"{person.first_name} {person.last_name}"
        person.save()


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0008_alter_demandeur_arrondissement"),
    ]

    operations = [
        migrations.RunPython(remove_duplicated_demandeurs, reverse_code=nothing),
    ]
