# Generated by Django 5.1.4 on 2025-02-21 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_projet", "0010_alter_demandeur_siret"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="perimetre",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="gsl_core.perimetre",
            ),
        ),
    ]
