# Generated by Django 5.1.4 on 2025-02-24 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0011_projet_perimetre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demandeur",
            name="arrondissement",
        ),
        migrations.RemoveField(
            model_name="demandeur",
            name="departement",
        ),
    ]
