# Generated by Django 5.1.4 on 2025-02-19 08:16

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0011_projet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("accepted", "✅ Accepté"),
                    ("refused", "❌ Refusé"),
                    ("processing", "🔄 En traitement"),
                    ("unanswered", "⛔️ Classé sans suite"),
                ],
                default="processing",
                max_length=50,
                verbose_name="Statut",
            ),
        ),
    ]
