# Generated by Django 5.1.4 on 2025-03-04 11:44

import django_fsm
from django.db import migrations


def update_projet_status(apps, schema_editor):
    Projet = apps.get_model("gsl_projet", "Projet")
    Projet.objects.filter(status="unanswered").update(status="dismissed")


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0014_merge_20250225_1159"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="status",
            field=django_fsm.FSMField(
                choices=[
                    ("accepted", "✅ Accepté"),
                    ("refused", "❌ Refusé"),
                    ("processing", "🔄 En traitement"),
                    ("dismissed", "⛔️ Classé sans suite"),
                ],
                default="processing",
                max_length=50,
                verbose_name="Statut",
            ),
        ),
        migrations.RunPython(update_projet_status),
    ]
