# Generated by Django 5.1.7 on 2025-03-31 11:02

import django.db.models.deletion
import django_fsm
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0017_projet_is_budget_vert"),
    ]

    operations = [
        migrations.CreateModel(
            name="DotationProjet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dotation",
                    models.CharField(
                        choices=[("DETR", "DETR"), ("DSIL", "DSIL")],
                        verbose_name="Dotation",
                    ),
                ),
                (
                    "status",
                    django_fsm.FSMField(
                        choices=[
                            ("accepted", "✅ Accepté"),
                            ("refused", "❌ Refusé"),
                            ("processing", "🔄 En traitement"),
                            ("dismissed", "⛔️ Classé sans suite"),
                        ],
                        default="processing",
                        max_length=50,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "assiette",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Assiette subventionnable",
                    ),
                ),
                (
                    "avis_commission_detr",
                    models.BooleanField(
                        help_text="Pour les projets de plus de 100 000 €",
                        null=True,
                        verbose_name="Avis commission DETR",
                    ),
                ),
                (
                    "projet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gsl_projet.projet",
                    ),
                ),
            ],
            options={
                "unique_together": {("projet", "dotation")},
            },
        ),
    ]
