# Generated by Django 5.1.7 on 2025-03-28 10:53

from django.db import migrations, models


def create_dotation(apps, schema_editor):
    Dotation = apps.get_model("gsl_projet", "Dotation")
    Dotation.objects.create(label="DSIL")
    Dotation.objects.create(label="DETR")


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0017_projet_is_budget_vert"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, verbose_name="Nom")),
            ],
        ),
        migrations.RunPython(create_dotation),
    ]
