# Generated by Django 5.1.7 on 2025-04-16 06:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0018_dotationprojet"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="status",
        ),
    ]
