# Generated by Django 5.1.7 on 2025-04-14 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0008_alter_perimetre_options"),
        ("gsl_projet", "0018_dotationprojet"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dotationprojet",
            options={
                "verbose_name": "Dotation projet",
                "verbose_name_plural": "Dotations projet",
            },
        ),
        migrations.CreateModel(
            name="CategorieDetr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("libelle", models.CharField(verbose_name="Libellé")),
                ("tri", models.IntegerField(verbose_name="Numéro d'ordre")),
                ("annee", models.IntegerField(verbose_name="Année")),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.departement",
                        verbose_name="Département",
                    ),
                ),
            ],
            options={
                "verbose_name": "Catégorie DETR",
                "verbose_name_plural": "Catégories DETR",
            },
        ),
        migrations.AddField(
            model_name="dotationprojet",
            name="detr_categories",
            field=models.ManyToManyField(
                to="gsl_projet.categoriedetr",
                verbose_name="Catégories d’opération DETR",
            ),
        ),
        migrations.AddConstraint(
            model_name="categoriedetr",
            constraint=models.UniqueConstraint(
                fields=("departement", "annee", "tri"),
                name="unique_by_departement_tri_annee",
            ),
        ),
    ]
