# Generated by Django 6.0.dev20250424131116 on 2025-05-12 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0019_alter_dotationprojet_options_categoriedetr_and_more"),
        ("gsl_projet", "0021_remove_projet_assiette_and_more"),
    ]

    operations = []
