# Generated by Django 5.2.6 on 2025-11-21 15:26

from django.db import migrations, models
from django.db.models import F


def copy_notified_at_from_programmation_to_projet(apps, schema_editor):
    """
    Copy notified_at from ProgrammationProjet to Projet.
    If a Projet has multiple ProgrammationProjet entries, use the most recent notified_at value.
    """
    Projet = apps.get_model("gsl_projet", "Projet")
    ProgrammationProjet = apps.get_model("gsl_programmation", "ProgrammationProjet")

    for projet in Projet.objects.all():
        # Get all ProgrammationProjet entries for this Projet, ordered by notified_at (most recent first)
        programmations = ProgrammationProjet.objects.filter(
            dotation_projet__projet=projet
        ).order_by("-notified_at")

        # Get the most recent notified_at value (first in ordered queryset)
        most_recent_notification = programmations.first()

        if most_recent_notification and most_recent_notification.notified_at:
            projet.notified_at = most_recent_notification.notified_at
            projet.save(update_fields=["notified_at"])


def reverse_copy_notified_at(apps, schema_editor):
    """
    Reverse migration: clear notified_at on Projet.
    """
    Projet = apps.get_model("gsl_projet", "Projet")
    ProgrammationProjet = apps.get_model("gsl_programmation", "ProgrammationProjet")

    for programmation in ProgrammationProjet.objects.all():
        projet = Projet.objects.get(pk=programmation.dotation_projet.projet.pk)
        programmation.notified_at = projet.notified_at
        programmation.save(update_fields=["notified_at"])
    Projet.objects.all().update(notified_at=None)


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0024_categoriedetr_is_current"),
        ("gsl_programmation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="notified_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date de notification"
            ),
        ),
        migrations.RunPython(
            copy_notified_at_from_programmation_to_projet,
            reverse_copy_notified_at,
        ),
    ]
