# Generated by Django 5.2.8 on 2025-12-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0026_remove_projet_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projet",
            name="is_budget_vert",
            field=models.BooleanField(
                default=False,
                verbose_name="Projet concourant à la transition écologique au sens budget vert",
            ),
        ),
    ]
