# Generated by Django 5.2.8 on 2025-12-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0027_alter_projet_is_budget_vert"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="is_acv",
            field=models.BooleanField(
                default=False,
                verbose_name="Projet rattaché à un programme Action coeurs de Ville (ACV)",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="is_autre_zonage_local",
            field=models.BooleanField(
                default=False, verbose_name="Projet rattaché à un autre zonage local"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="is_contrat_local",
            field=models.BooleanField(
                default=False, verbose_name="Projet rattaché à un contrat local"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="is_frr",
            field=models.BooleanField(
                default=False, verbose_name="Projet situé en FRR"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="is_pvd",
            field=models.BooleanField(
                default=False,
                verbose_name="Projet rattaché à un programme Petites villes de demain (PVD)",
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="is_va",
            field=models.BooleanField(
                default=False,
                verbose_name="Projet rattaché à un programme Villages d'avenir",
            ),
        ),
    ]
