# Generated by Django 5.2.8 on 2026-01-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0028_projet_is_acv_projet_is_autre_zonage_local_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="autre_zonage_local",
            field=models.CharField(blank=True, verbose_name="Nom du zonage local"),
        ),
        migrations.AddField(
            model_name="projet",
            name="contrat_local",
            field=models.CharField(blank=True, verbose_name="Nom du contrat local"),
        ),
    ]
