# Generated by Django 5.2.8 on 2026-02-09 17:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0029_projet_autre_zonage_local_projet_contrat_local"),
    ]

    operations = [
        migrations.AddField(
            model_name="dotationprojet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dotationprojet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Date de création",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projet",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="projetnote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="projetnote",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
    ]
