# Generated by Django 5.2.8 on 2026-02-10 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "gsl_projet",
            "0030_dotationprojet_created_at_dotationprojet_updated_at_and_more",
        ),
        ("gsl_projet", "0030_remove_projet_perimetre"),
    ]

    operations = []
