# Generated by Django 5.2.8 on 2026-02-26 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0031_merge_20260210_1653"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projet",
            name="free_comment",
        ),
        migrations.AddField(
            model_name="projet",
            name="comment_1",
            field=models.TextField(
                blank=True, default="", verbose_name="Commentaire 1"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="comment_2",
            field=models.TextField(
                blank=True, default="", verbose_name="Commentaire 2"
            ),
        ),
        migrations.AddField(
            model_name="projet",
            name="comment_3",
            field=models.TextField(
                blank=True, default="", verbose_name="Commentaire 3"
            ),
        ),
    ]
