# Generated by Django 5.2.8 on 2026-03-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0032_remove_projet_free_comment_projet_comment_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projet",
            name="dotations_has_been_updated_in_app",
            field=models.BooleanField(
                default=False, verbose_name="Dotations modifiées dans Turgot"
            ),
        ),
    ]
