# Generated by Django 5.2.8 on 2026-03-10 14:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0033_projet_dotations_updated_in_app"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dotationprojet",
            name="assiette",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Assiette subventionnable",
            ),
        ),
    ]
