# Generated by Django 5.2.8 on 2026-03-12 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_projet", "0034_alter_dotationprojet_assiette"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dotationprojet",
            name="assiette",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Assiette subventionnable",
            ),
        ),
    ]
