from django.urls import path

from gsl_simulation.views import simulation_views
from gsl_simulation.views.decorators import (
    simulation_must_be_visible_by_user,
)
from gsl_simulation.views.simulation_projet_notes_views import (
    ProjetNoteEditView,
    SimulationProjetNotesView,
    get_note_card,
)
from gsl_simulation.views.simulation_projet_views import (
    EditAssietteView,
    EditMontantView,
    EditTauxView,
    ProgrammationStatusUpdateView,
    ProjetFormView,
    RefreshSimulationRowView,
    SimulationProjetDetailView,
    SimulationProjetStatusUpdateView,
    patch_dotation_projet,
)
from gsl_simulation.views.simulation_views import (
    SimulationColumnsVisibilityView,
    SimulationCreateView,
    SimulationDeleteView,
    SimulationRenameView,
)

urlpatterns = [
    path(
        "liste/",
        simulation_views.SimulationListView.as_view(),
        name="simulation-list",
    ),
    path(
        "voir/<slug:slug>/",
        simulation_must_be_visible_by_user(
            simulation_views.SimulationDetailView.as_view()
        ),
        name="simulation-detail",
    ),
    path(
        "<int:pk>/supprimer/",
        SimulationDeleteView.as_view(),
        name="simulation-delete",
    ),
    path(
        "voir/<slug:slug>/columns-visibility/",
        SimulationColumnsVisibilityView.as_view(),
        name="simulation-columns-visibility",
    ),
    path(
        "<int:pk>/renommer/",
        SimulationRenameView.as_view(),
        name="simulation-rename",
    ),
    path(
        "voir/<slug:slug>/<str:type>/",
        simulation_must_be_visible_by_user(
            simulation_views.FilteredProjetsExportView.as_view()
        ),
        name="simulation-projets-export",
    ),
    path(
        "projet-detail/<int:pk>/",
        SimulationProjetDetailView.as_view(),
        name="simulation-projet-detail",
    ),
    path(
        "projet-detail/<int:pk>/notes/",
        SimulationProjetNotesView.as_view(),
        name="simulation-projet-notes",
    ),
    path(
        "edit-assiette/<int:pk>/",
        EditAssietteView.as_view(),
        name="edit-assiette",
    ),
    path(
        "edit-montant/<int:pk>/",
        EditMontantView.as_view(),
        name="edit-montant",
    ),
    path(
        "edit-taux/<int:pk>/",
        EditTauxView.as_view(),
        name="edit-taux",
    ),
    path(
        "refresh-row/<int:pk>/",
        RefreshSimulationRowView.as_view(),
        name="refresh-simulation-row",
    ),
    path(
        "<int:pk>/simuler/<str:status>/",
        SimulationProjetStatusUpdateView.as_view(),
        name="simulation-projet-update-simulation-status",
    ),
    path(
        "<int:pk>/programmer/<str:status>/",
        ProgrammationStatusUpdateView.as_view(),
        name="simulation-projet-update-programmed-status",
    ),
    path(
        "creation-simulation",
        SimulationCreateView.as_view(),
        name="simulation-form",
    ),
    path(
        "modifier-le-projet-d-un-projet-de-simulation/<int:pk>/",
        ProjetFormView.as_view(),
        name="patch-projet",
    ),
    path(
        "modifier-le-projet-de-dotation-d-un-projet-de-simulation/<int:pk>/",
        patch_dotation_projet,
        name="patch-dotation-projet",
    ),
    # Annotations
    path(
        "simulation_projet/<int:pk>/notes/<int:note_id>/edit",
        ProjetNoteEditView.as_view(),
        name="get-edit-projet-note",
    ),
    path(
        "simulation_projet/<int:pk>/notes/<int:note_id>",
        get_note_card,
        name="get-note-card",
    ),
]
