# Generated by Django 6.0.5 on 2026-06-03 13:00

import django.contrib.admin.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("gsl_historique", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollegueLogEntry",
            fields=[],
            options={
                "verbose_name": "Entrée d'historique utilisateur",
                "verbose_name_plural": "Entrées d'historique des utilisateurs",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("admin.logentry",),
            managers=[
                ("objects", django.contrib.admin.models.LogEntryManager()),
            ],
        ),
    ]
