"""
Django settings for gsl project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
import sys
from pathlib import Path

import dj_database_url
from csp.constants import NONCE, SELF
from dotenv import load_dotenv
from sentry_sdk.integrations.logging import LoggingIntegration

load_dotenv()  # take environment variables from .env.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG")
ENV = os.getenv("ENV")
if ENV not in ("dev", "test", "staging", "prod", "demo"):
    raise ValueError(
        f"ENV must be one of 'dev', 'test', 'staging' or 'prod'. Got {ENV} instead."
    )

# We support a comma-separated list of allowed hosts.
ENV_SEPARATOR = ","
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(ENV_SEPARATOR)

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "mozilla_django_oidc",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_celery_results",
    "django_celery_beat",
    # dependencies:
    "csp",
    "widget_tweaks",
    "dsfr",
    "import_export",
    "formtools",
    "django_htmx",
    "django_filters",
    "django_extensions",
    # gsl apps:
    "ui",
    "gsl_core",
    "gsl_demarches_simplifiees",
    "gsl_projet",
    "gsl_programmation",
    "gsl_simulation",
    "gsl_notification",
    "gsl_pages",
    "gsl_oidc",
]


MIDDLEWARE = [
    "csp.middleware.CSPMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "gsl_oidc.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django_htmx.middleware.HtmxMiddleware",
    "gsl_core.middlewares.CheckPerimeterMiddleware",
]

if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

    INTERNAL_IPS = [
        "127.0.0.1",
    ]

AUTHENTICATION_BACKENDS = [
    "gsl_oidc.backends.OIDCAuthenticationBackend",
    "django.contrib.auth.backends.ModelBackend",
]

AUTH_USER_MODEL = "gsl_core.Collegue"
ROOT_URLCONF = "gsl.urls"
LANGUAGE_CODE = "fr"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "dsfr.context_processors.site_config",
                "gsl.utils.context_processors.export_vars",
            ],
        },
    },
]

STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}


WSGI_APPLICATION = "gsl.wsgi.application"


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/
STATIC_URL = "static/"
STATIC_ROOT = "staticfiles"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = os.getenv("MEDIA_ROOT", BASE_DIR / "media")

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASE_URL = os.getenv("DATABASE_URL")
if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    raise ValueError("Please set the DATABASE_URL environment variable")

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 15,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "fr-fr"

TIME_ZONE = "Europe/Paris"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Connection to Démarches simplifiées’ API
DS_API_TOKEN = os.getenv("DS_API_TOKEN", "")
DS_API_URL = os.getenv(
    "DS_API_URL", "https://demarche.numerique.gouv.fr/api/v2/graphql"
)
DS_CLIENT_ID = os.getenv("DS_CLIENT_ID", ENV)
LOGIN_URL = "/comptes/login/"

# Redirect after login/logout - used by OIDC backends

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# Logs
APP_LOGGING_LEVEL = os.getenv("LOGGING_LEVEL", "INFO")
DJANGO_LOGGING_LEVEL = os.getenv("DJANGO_LOGGING_LEVEL", "ERROR")
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "()": "gsl.utils.logging_formatters.DynamicExtraFormatter",
            "format": "%(name)-12s %(levelname)-8s %(message)s",
        },
        "django.server": {
            "()": "django.utils.log.ServerFormatter",
            "format": "[{server_time}] {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "verbose",
        },
        "django.server": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "django.server",
        },
        "sentry": {
            "class": "sentry_sdk.integrations.logging.SentryLogsHandler",
            "formatter": "verbose",
        },
    },
    "loggers": {
        "root": {
            "handlers": ["console", "sentry"],
            "level": APP_LOGGING_LEVEL,
            "propagate": True,
        },
        "django": {
            "handlers": ["console", "sentry"],
            "level": DJANGO_LOGGING_LEVEL,
            "propagate": False,
        },
        "django.server": {
            "handlers": ["django.server"],
            "level": "INFO",
            "propagate": False,
        },
        "celery": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "celery.worker": {
            "handlers": ["console", "sentry"],
            "level": DJANGO_LOGGING_LEVEL,
            "propagate": False,
        },
        "gunicorn": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "gunicorn.error": {
            "handlers": ["console", "sentry"],
            "level": "INFO",
            "propagate": False,
        },
        "pikepdf": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}

# Init Sentry if the DSN is defined
SENTRY_DSN = os.getenv("SENTRY_DSN", None)
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    SENTRY_ENV = os.getenv("SENTRY_ENV", "unknown")
    SENTRY_TRACES_SAMPLE_RATE = os.getenv("SENTRY_TRACES_SAMPLE_RATE", 0.1)
    SENTRY_PROFILES_SAMPLE_RATE = os.getenv("SENTRY_PROFILES_SAMPLE_RATE", None)
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[
            DjangoIntegration(),
            LoggingIntegration(
                sentry_logs_level=None,
            ),
        ],
        environment=SENTRY_ENV,
        enable_logs=True,
        traces_sample_rate=float(SENTRY_TRACES_SAMPLE_RATE),
        profiles_sample_rate=(
            float(SENTRY_PROFILES_SAMPLE_RATE) if SENTRY_PROFILES_SAMPLE_RATE else None
        ),
    )


# Connection to "Pro Connect" (OIDC)
PROCONNECT_DOMAIN = os.getenv("PROCONNECT_DOMAIN", "fca.integ01.dev-agentconnect.fr")
PROCONNECT_ISSUER = os.getenv("PROCONNECT_ISSUER", f"{PROCONNECT_DOMAIN}/api/v2")

OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_CLIENT_ID = os.getenv("PROCONNECT_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = os.getenv("PROCONNECT_CLIENT_SECRET")
OIDC_RP_SCOPES = "openid email given_name usual_name uid siret idp_id"
OIDC_OP_JWKS_ENDPOINT = f"https://{PROCONNECT_ISSUER}/jwks"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"https://{PROCONNECT_ISSUER}/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"https://{PROCONNECT_ISSUER}/token"
OIDC_OP_USER_ENDPOINT = f"https://{PROCONNECT_ISSUER}/userinfo"
OIDC_OP_LOGOUT_ENDPOINT = f"https://{PROCONNECT_ISSUER}/session/end"

OIDC_AUTH_REQUEST_EXTRA_PARAMS = {"acr_values": "eidas1"}
OIDC_RENEW_ID_TOKEN_EXPIRY_SECONDS = 4 * 60 * 60
OIDC_STORE_ID_TOKEN = True
ALLOW_LOGOUT_GET_METHOD = True

# Celery configuration

CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://localhost:6379")
CELERY_ACCEPT_CONTENT = {"application/json"}
CELERY_RESULT_SERIALIZER = "json"
CELERY_TASK_SERIALIZER = "json"
CELERY_TIMEZONE = "Europe/Paris"
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
CELERY_WORKER_HIJACK_ROOT_LOGGER = False


# CSP Configuration

CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": [SELF],
        "img-src": [SELF, "data:", "stats.beta.gouv.fr"],
        "style-src": [SELF, NONCE],
        "script-src": [SELF, NONCE, "stats.beta.gouv.fr"],
        "connect-src": [SELF, "https://stats.beta.gouv.fr"],
    },
}

CONTENT_SECURITY_POLICY_REPORT_ONLY = {}

# Cookie configuration

CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG

# Storage
AWS_ACCESS_KEY_ID = os.getenv("SCALEWAY_S3_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("SCALEWAY_S3_SECRET")
AWS_STORAGE_BUCKET_NAME = os.getenv("SCALEWAY_BUCKET")
AWS_S3_REGION_NAME = os.getenv("SCALEWAY_S3_REGION", "fr-par")
AWS_S3_ENDPOINT_URL = os.getenv(
    "AWS_S3_ENDPOINT_URL", f"https://s3.{AWS_S3_REGION_NAME}.scw.cloud"
)

MAX_POST_FILE_SIZE_IN_MO = os.getenv("MAX_POST_FILE_SIZE_IN_MO", 20)
