name: Django CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    types: [ "opened", "synchronize", "reopened" ]
  merge_group:
  workflow_call:

permissions:
  contents: read

jobs:
  lint-python:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Check linting
      run: |
        ruff check
        ruff format --check

    - name: Check templates format
      run: djlint . --check

  lint-frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: bahmutov/npm-install@v1

    - name: Check css format
      run: npm run lint:css

    - name: Check js format
      run: npm run format:js

  tests:
    environment: test
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ github.event_name != 'pull_request' && format('postgres://{0}:{1}@{2}:{3}/{4}', vars.DATABASE_USER, vars.DATABASE_PASSWORD, vars.DATABASE_HOST, vars.DATABASE_PORT, vars.DATABASE_NAME) || 'sqlite://:memory:' }}
      SECRET_KEY: ${{ vars.SECRET_KEY }}
      ENV: test

    services:
      postgres:
        image: ${{ github.event_name != 'pull_request' && 'postgres:16' || '' }}
        env:
          POSTGRES_DB: ${{ vars.DATABASE_NAME }}
          POSTGRES_USER: ${{ vars.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ vars.DATABASE_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: "3.13"
        cache: 'pip'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt

    - name: Check migrations
      run: python manage.py makemigrations --check --dry-run

    - name: Run Tests
      run: |
        python -m pytest --create-db
