# Generated by Django 5.1.1 on 2024-11-06 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0002_collegue_proconnect_chorusdt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commune",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insee_code",
                    models.CharField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code INSEE",
                    ),
                ),
                ("name", models.CharField(verbose_name="Nom")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Departement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insee_code",
                    models.CharField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code INSEE",
                    ),
                ),
                ("name", models.CharField(verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Département",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insee_code",
                    models.CharField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code INSEE",
                    ),
                ),
                ("name", models.CharField(verbose_name="Nom")),
            ],
            options={
                "verbose_name": "Région",
            },
        ),
        migrations.CreateModel(
            name="Adresse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.TextField(verbose_name="Adresse complète")),
                ("postal_code", models.CharField(verbose_name="Code postal")),
                ("street_address", models.CharField(verbose_name="Adresse")),
                (
                    "commune",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.commune",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="commune",
            name="departement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gsl_core.departement"
            ),
        ),
        migrations.CreateModel(
            name="Arrondissement",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "insee_code",
                    models.CharField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Code INSEE",
                    ),
                ),
                ("name", models.CharField(verbose_name="Nom")),
                (
                    "departement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="gsl_core.departement",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="departement",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="gsl_core.region"
            ),
        ),
    ]
