# Generated by Django 5.1.4 on 2025-01-10 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0006_commune_arrondissement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perimetre",
            options={"verbose_name": ("Périmètre",)},
        ),
    ]
