# Generated by Django 5.1.4 on 2025-01-20 20:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0007_alter_perimetre_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="perimetre",
            options={"verbose_name": "Périmètre"},
        ),
    ]
