# Generated by Django 5.2.8 on 2026-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0012_departement_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="collegue",
            name="comment",
            field=models.TextField(blank=True, default="", verbose_name="Commentaire"),
        ),
    ]
