# Generated by Django 5.2.8 on 2026-02-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0012_departement_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collegue",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Donne accès au site d'administration avec toutes les permissions (ajout, modification, suppression) sur les modèles métiers de Turgot.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="collegue",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Administration technique : donne toutes les permissions y compris la gestion des utilisateurs et de leurs droits.",
                verbose_name="superuser status",
            ),
        ),
    ]
