# Generated by Django 5.2.8 on 2026-02-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0013_collegue_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adresse",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="adresse",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="arrondissement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="arrondissement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="commune",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="departement",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="perimetre",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="perimetre",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Date de création"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Date de modification"
            ),
        ),
    ]
