# Generated by Django 6.0.7 on 2026-09-18 07:24

import gsl.core.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0018_merge_0017_commune_siren_0017_importstate"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="collegue",
            managers=[
                ("objects", gsl.core.models.CollegueManager()),
            ],
        ),
    ]
