# Generated by Django 6.0.7 on 2026-09-28 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0019_alter_collegue_managers"),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkActionsJob",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(max_length=64, verbose_name="Action")),
                ("object_ids", models.JSONField(default=list)),
                ("params", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("running", "En cours"),
                            ("done", "Terminé"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("processed", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(default=list)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Action en masse",
                "verbose_name_plural": "Actions en masse",
                "ordering": ("-created_at",),
            },
        ),
    ]
