# Generated by Django 6.0.7 on 2026-09-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gsl_core", "0020_bulkactionsjob"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bulkactionsjob",
            old_name="errors",
            new_name="report",
        ),
        migrations.AddField(
            model_name="bulkactionsjob",
            name="lock_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddConstraint(
            model_name="bulkactionsjob",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ("pending", "running")),
                    models.Q(("lock_key", ""), _negated=True),
                ),
                fields=("action", "lock_key"),
                name="uq_bulkactionsjob_active_per_action_and_lock_key",
            ),
        ),
    ]
